alphagov/email-alert-frontend

- README.md
> Add example URL to README

- app/assets/stylesheets/taxonomy-signup.scss
- app/views/taxonomy_signups/confirm.html.erb
- app/views/taxonomy_signups/new.html.erb
> Add back buttons to taxonomy email signup pages

- app/views/taxonomy_signups/_taxon.html.erb
- app/views/taxonomy_signups/confirm.html.erb
- app/views/taxonomy_signups/new.html.erb
- features/step_definitions/taxonomy_email_alert_steps.rb
> Visual and navigation tweaks on signup pages

- app/models/weekly_email_volume.rb
- app/views/taxonomy_signups/confirm.html.erb
- app/views/taxonomy_signups/new.html.erb
- features/step_definitions/taxonomy_email_alert_steps.rb
> Minor copy change on email signup pages

- app/views/layouts/application.html.erb
- app/views/unsubscriptions/confirm.html.erb
- app/views/unsubscriptions/confirmed.html.erb
- config/initializers/assets.rb
This PR contains @nickcolley's changes to our css handling and some view changes to the unsubscribe page. See individual commit messages for details.
> Css and view changes

- .rubocop.yml
- Gemfile
- Gemfile.lock
- Jenkinsfile
- Rakefile
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/taxonomy-signup.scss
- app/controllers/email_alert_signups_controller.rb
- app/controllers/taxonomy_signups_controller.rb
- app/controllers/unsubscriptions_controller.rb
- app/models/email_alert_signup.rb
- app/models/taxonomy_signup.rb
- app/models/weekly_email_volume.rb
- config/cucumber.yml
- config/environments/production.rb
- config/initializers/services.rb
- config/routes.rb
- features/step_definitions/taxonomy_email_alert_steps.rb
- features/support/env.rb
- lib/govuk_content_schema_examples.rb
- lib/tasks/lint.rake
- lib/tasks/publishing_api.rake
- spec/controllers/unsubscriptions_controller_spec.rb
- spec/models/email_alert_signup_spec.rb
- spec/models/taxonomy_signup_spec.rb
- spec/models/weekly_email_volume_spec.rb
- spec/rails_helper.rb
This PR sets up linting and fixes all existing linting errors.
> Set up linting

- LICENCE
- README.md
Add a LICENCE file and link from the README.md
> Add LICENCE

- Dockerfile
This commit updates ruby to 2.4.2 in the Dockerfile to match the `.ruby-version` file.
> Update ruby version in Dockerfile

- Gemfile
- Gemfile.lock
- app/controllers/subscriptions_controller.rb
- app/views/subscriptions/complete.html.erb
- app/views/subscriptions/new_address.html.erb
- app/views/subscriptions/new_frequency.html.erb
- spec/features/subscribe_spec.rb
Paired with @keithiopia on these. It comprises of lots of small copy changes and some tweaks to how we render and use components.
> Various content and semantic updates to subscriber flow

- Gemfile
- Gemfile.lock
We can install this gem on our infrastructure again.
> Remove the ffi pin

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
- features/step_definitions/taxonomy_email_alert_steps.rb
This replaces the "Is there anything wrong?" link with the new feedback component. This component asks the user if the page is useful and reports the results to Google Analytics.
See https://github.com/alphagov/govuk_publishing_components/pull/163 for the component.
https://trello.com/c/eKtXGtBD
> Use the feedback component

- app/views/unsubscriptions/confirmed.html.erb
- spec/controllers/unsubscriptions_controller_spec.rb
https://github.com/alphagov/email-alert-frontend/pull/143 with test changes.
> Copy change to confirmation message

- config/routes.rb
https://trello.com/c/OanAgv6p
Closes https://github.com/alphagov/email-alert-frontend/issues/102.
> Expose the component guide on Heroku

- app/controllers/authentication_controller.rb
- app/controllers/subscriptions_management_controller.rb
- spec/controllers/authentication_controller_spec.rb
- spec/controllers/subscriptions_management_controller_spec.rb
This commit enables the subscription management frontend.
> Enable subscription management frontend

- app/views/subscriptions_management/index.html.erb
Change frequency text so that it matches the update frequency view. 
For Alan.
> Change 'immediately' to 'as soon as they happen'

- app/assets/stylesheets/print.scss
- app/views/layouts/application.html.erb
For consistency with other applications. This includes the print styles for the components.
https://docs.google.com/spreadsheets/d/1J-0IPyr2ycPuw1IWOIoX0o9Tk9nF35D0DJdsj_ylLQE/edit
> Add print stylesheet

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/views/email_alert_signups/new.html.erb
- app/views/taxonomy_signups/new.html.erb
- features/step_definitions/email_alert_steps.rb
- features/support/slimmer_helper.rb
- spec/features/subscribe_spec.rb
See commits for details.
https://trello.com/c/pU7YINt1/45-move-all-components-from-static-into-the-gem
> Remove last components from Static

- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
It doesn't seem to be used or referenced anymore
> Remove phantomjs

- app/views/subscriptions/new_address.html.erb
- app/views/subscriptions/new_frequency.html.erb
This will make this form much easier to target via css selectors.
https://trello.com/c/qM2a6irn
> Add id to email subscription forms

- config/environments/development.rb
https://github.com/alphagov/govuk-docker/issues/176
> Fix allowed hosts to support Docker

- .rubocop.yml
- app/controllers/subscriber_authentication_controller.rb
- app/controllers/subscriptions_controller.rb
- app/controllers/subscriptions_management_controller.rb
- app/models/email_alert_signup.rb
trello: https://trello.com/c/Lijki8aj/1584-3-enable-rails-rubocop-rules-via-rubocop-govuk-on-all-our-rails-apps
> Enable rails-specific rules for rubocop-govuk

- app/assets/stylesheets/application.scss
https://trello.com/c/v4ZdPW3H/117-switch-to-new-colours-in-email-alert-frontend
> Remove flag to enabled new colours

- config/locales/subscriptions_management.yml
Making it clearer that some emails may still be sent after the request is made.
https://trello.com/c/eeMr0zaf/864-content-changes-to-email-unsubscribe-page
> Reword unsubscription notification

- app/models/email_volume/weekly_email_volume.rb
https://trello.com/c/dH9zUBN4/135-placeholder-introduce-an-email-signup-route-for-taxons
This isn't used anywhere.
> Remove unused exception class

- .rubocop.yml
- Gemfile
- Rakefile
- lib/tasks/lint.rake
- lib/tasks/publishing_api.rake
- lib/tasks/rspec.rake
- lib/tasks/test.rake
- spec/controllers/content_item_signups_controller_spec.rb
- spec/features/content_item_signup_spec.rb
- spec/features/email_alert_signup_spec.rb
- spec/features/topic_signup_back_spec.rb
- spec/models/weekly_email_volume_spec.rb
- There's quite a bit going on here. See individual commits for details.
https://trello.com/c/5Gob6WUL/147-for-everyone-ensure-that-rubocop-runs-as-part-of-bundle-exec-rake-as-one-of-the-default-tasks
> Run RuboCop as part of `bundle exec rake`

- app/controllers/content_item_signups_controller.rb
- app/models/content_item_subscriber_list.rb
This allows params from Collections for users to start their sign up journey here.
https://trello.com/c/UmDXU47V
[Corresponding Collections pr](https://github.com/alphagov/collections/pull/1749)
> Add Collections "topic" signup support

- config/locales/subscriptions_management.yml
https://trello.com/c/RPBoOye6/440-start-the-switch-immediate-to-digest-experiment
This is about to become inaccurate, as we automatically switch many
subscriptions to daily digest.
> Remove references to 'choice' of frequency

- .gitignore
- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
We should always monitor how much code is exercised when our tests run.
> Add SimpleCov to report coverage after tests

- spec/controllers/content_item_signups_controller_spec.rb
- spec/features/content_item_signup_spec.rb
https://trello.com/c/mk5M2aKD/619-general-design-and-stylistic-updates-to-signup-workflow
Please see the commits for more details.
> Improve tests for generic content item signup

- spec/controllers/subscriber_authentication_controller_spec.rb
- spec/controllers/subscription_authentication_controller_spec.rb
https://trello.com/c/hdOrNhuC/669-sign-in-after-subscribing
Please see the commits for more details.
> Improve controller tests for subscriber auth

- README.md
https://trello.com/c/oYRFCtBm/668-iterate-error-content-and-behaviour-for-new-signup-workflow
Relates to: https://github.com/alphagov/email-alert-frontend/pull/971
> Remove last use of the legacy "topic" query param

- app/views/subscriptions_management/index.html.erb
This was recently changed, and updating here avoids an unnecessary
redirect.
> Update link to help page for subscribing

- app/controllers/single_page_subscriptions_controller.rb
- spec/controllers/single_page_subscriptions_controller_spec.rb
If a user is already logged into their GOV.UK account and clicks the single
page notifications button on a page, we now check if they're already
subscribed. If they are, unsubscribe them and redirect them back to the
page.
This exists on the same route and uses the same params as the subscriptions. 
This allows us to do a graceful fallback if the JavaScript that updates the single 
page notifications button on the content page fails for any reason.
[Trello](https://trello.com/c/WLWvG3sL/1117-implement-single-page-unsubscribe)
> Add single page unsubscribe

- app/views/development/index.html.erb
We forgot to switch this over, only really of use for testing on Dev
> Correct development test form to use base_path not topic

- app/controllers/single_page_subscriptions_controller.rb
- spec/controllers/single_page_subscriptions_controller_spec.rb
[Trello card](https://trello.com/c/05BtVxFZ/1100-prep-to-qa-single-page-notifications-journeys)
> Return to single-page after confirmation

- app/controllers/account_subscriptions_controller.rb
See commit messages for more details.
> Fix a couple of issues with the "already subscribed" feature

- config/locales/account_subscriptions.yml
[Trello](https://trello.com/c/HVS5kp0P/1222-content-change-move-to-new-account-in-merge-page)
Slight clarification for consistency
> Content change for confirm emails page

- config/locales/account_subscriptions.yml
Updates the notice added in #1303 to make the first sentence read better.
---
[Trello](https://trello.com/c/ZmuMTQy5/1370-remove-cookies-and-feedback)
[Discussion on content](https://gds.slack.com/archives/C01H13E9YP8/p1652795034146639?thread_ts=1652774515.861939&cid=C01H13E9YP8)
> Update account privacy text

- config/locales/single_page_subscriptions.yml
https://govukverify.atlassian.net/browse/GUA-224
| Before  | After |
| ------------ | ------------ |
| ![before](https://user-images.githubusercontent.com/7116819/174646212-2669816e-f3ed-4978-81ab-50fef5abef96.png)  | ![after](https://user-images.githubusercontent.com/7116819/174646293-7f984bef-0f07-4dfc-ab9d-473df8047626.png)  |
-------
> Update interrupt page content for account MVP

- .github/workflows/deploy.yaml
> Fix indent in deploy.yaml

- Gemfile
> We already point to floating patch version of Ruby

- app/views/govuk_account_signups/show.html.erb
- config/locales/single_page_subscriptions.yml
Small content updates for:
https://trello.com/c/yxBLErqj/2135-improve-account-journeys-in-email-alert-frontend
> Further tweaks to single page subscriptions content

- app/controllers/subscriptions_management_controller.rb
https://trello.com/c/9o9pvE3a/2146-implement-one-login-cross-service-header-on-the-email-subscriptions-service
> - To help us here in One Login improve the component
> - To provide email subscriptions service users with the navigation improvements we’re already confident about following our testing
- https://github.com/alphagov/govuk_publishing_components/pull/3659
- https://github.com/alphagov/static/pull/3170
> Implement One Login "cross service header"

- .github/workflows/deploy.yml
- Dockerfile
This starts giving us ARM builds for the Email Frontend. (We did the Email API quite some time ago).
> Start ARM builds for Email Frontend

- .github/workflows/actionlint.yml
This add the Action Lint checks to Email Alert Frontend
> Add Actionlint to Email Alert Frontend
