app/models/email_alert_signup.rb, app/views/email_alert_signups/new.html.erb, features/email_alerts.feature, features/step_definitions/email_alert_steps.rb, features/support/email_alert_signup_helper.rb
When a email alert signup starts with "/government" in its base path, we should be displaying the government navigation. This commit does that by checking the `base_path` and getting the second section of this to mark the active link in the nav. This follows the same approach as Finder Frontend.
Screenshot:
=> Render gov nav if base_path has "/government"

app/controllers/email_alert_signups_controller.rb
When hitting the create action, we don't want to protect from forgery as
caching interferes with the token.
=> Don't protect_from_forgery on create

app/models/email_alert_signup.rb, features/step_definitions/email_alert_steps.rb, spec/models/email_alert_signup_spec.rb
If a different govdelivery-title is present, use that for the name of
the govdelivery topic when creating the subscription params.
=> Use govdelivery-title if available

Gemfile, Gemfile.lock
Adds support for PLEK_HOSTNAME_PREFIX to enable it to talk to the draft content-store.
=> Bump Plek to 1.11.0.

Gemfile, Gemfile.lock, app/controllers/application_controller.rb
This should be a no-op change to app behaviour. The Slimmer upgrade will cancel
out the removal of explicitly setting slimmer template.
Note; these leaves `include Slimmer::Headers` in `ApplicationController` as its
depended on by `set_slimmer_dummy_artefact` in `EmailAlertSignupsController`.
Slimmer 9.0.0 switched to `core_layout` [1] as the default layout, which is the
modern/recommend layout. Apps using legacy layout should set it explicitly, so
they're easily identified as outliers to be fixed.
Apps using `core_layout` shouldn't set slimmer template at all, which simplies
the app controller code too.
[1] https://github.com/alphagov/slimmer/pull/136
=> Upgrade Slimmer, stop explicitly setting 'core_layout'

Gemfile, Gemfile.lock, app/models/email_alert_signup.rb, features/step_definitions/email_alert_steps.rb, features/support/email_alert_signup_helper.rb, spec/models/email_alert_signup_spec.rb
Please merge https://github.com/alphagov/email-alert-api/pull/93 first.
This makes use of a new field on email_alert_signup content items -
'email_alert_type' - to construct the payload for the email-alert-api
when sending a subscription request. Using the field means the frontend
doesn't need to have explicit knowledge of the types of email alert that
are supported. Currently only policy subscriptions are handled in this
way, but the implementation leaves open the possibility of migrating
topics (for example) to make use of the email-alert-frontend as well.
Govuk content schemas determine which values of email_alert_type are valid,
ensuring that the email-alert-api receives expected values.
=> Use the email_alert_type when constructing the email-alert-api payload

app/models/email_alert_signup.rb
Email alert signup content items are currently being migrated to use the
field 'signup_tags' instead of 'tags' to describe the content item being
subscribed to. This change provides a temporary conditional check on the
presence of that field while the schema change is being reviewed and
deployed.
=> Add conditional check on subscription params tag construction

features/step_definitions/email_alert_steps.rb, spec/models/email_alert_signup_spec.rb
Previous merge was green on CI prior to a set of govuk-content-schema
changes going in. As it wasn't rebuilt after that change, these updates are
required to fix master. In the process of doing so, this commit removes
some tests of questionable value.
=> Test fixes and cleanup for email alert signup

Gemfile, Gemfile.lock, app/models/email_alert_signup.rb, features/step_definitions/email_alert_steps.rb, spec/models/email_alert_signup_spec.rb
**We will merge the pull requests ourselves in the Publishing Platform team when everyone's happy.**
https://trello.com/c/oqGCU2XP/525-add-email-signup-links-to-travel-advice-on-frontend
We've been migrating travel advice over to use the new email-alert-frontend workflow rather than the old pagewatch workflow.
Whilst doing this work, we noticed that policy publisher passes through subscriber list information as implicit links on the signup content item (which should really be reserved for more general associations with other content items). After talking with @tijmenb and @mobaig in Finding Things we concluded that the details hash is the best place for that information.
Therefore, this work consists of four parts:
1) An update to travel advice publisher to create the new email alert …
=> Update schemas to use the new subscriber_list details format

app/views/email_alert_signups/new.html.erb, app/views/layouts/application.html.erb
This commit adds meta description tags to all email alert pages, the contents of which are set to the summary associated with the relevant alert. This adds descriptions to external search engine results when the pages are re-indexed.
Trello: https://trello.com/c/bbAwFAQ1/108-add-meta-descriptions-to-pages-missing-them
=> Add meta descriptions

Gemfile, Gemfile.lock, README.md, app/controllers/application_controller.rb, app/controllers/email_alert_signups_controller.rb, app/models/email_alert_signup.rb, features/support/env.rb, spec/models/email_alert_signup_spec.rb
The breadcrumbs in this application seem to never have worked. The code constructs a hash and passes this into slimmer as a "dummy artefact". But this only works for pages that are rendered with the `core_layout ` layout from static, and these pages are rendered with `core_layout`.
The first commit removes the code, since it's not working. It allows us to upgrade to a new slimmer version in the second.
https://trello.com/c/7wohUbyo
=> Remove non-working breadcrumb code

Gemfile, Gemfile.lock, app/controllers/email_alert_signups_controller.rb, app/models/email_alert_signup.rb, spec/models/email_alert_signup_spec.rb
Need the latest version of the adapters in order to use the
govuk_taxonomy_helpers gem and its breadcrumb functionality.
=> Upgrade gds-api-adapters from 29.4.0 to 40.1

app/controllers/taxonomy_signups_controller.rb, app/models/weekly_email_volume.rb, app/views/taxonomy_signups/confirm.html.erb, features/step_definitions/taxonomy_email_alert_steps.rb, spec/models/weekly_email_volume_spec.rb
Add very rough guesses about the weekly volume of email a user can
expect depending on which level of the taxonomy they sign up to. These
figures are based on analysis of historical email volume.
Note that the original requirement here was to treat 2nd level taxons that are also bottom level taxons as being LOW frequency - I've made a decision here to simplify the implementation because of time constraints. This is unlikely to be problematic given these numbers are very rough estimates. Discussed and agreed with Rob Rankin.
=> Add email volume estimates to signup confirm page

app/controllers/taxonomy_signups_controller.rb
CSRF protection on this action leads to InvalidAuthenticityToken
exceptions, seemingly because of caching on the confirm page. Skip
protection so that the user can be taken to GovDelivery to manage their
subscription.
=> Exclude taxonomy signup action from request forgery protection

app/views/taxonomy_signups/confirm.html.erb, app/views/taxonomy_signups/new.html.erb
=> Collapse taxonomy signup breadcrumbs on mobile

app/controllers/taxonomy_signups_controller.rb, features/step_definitions/taxonomy_email_alert_steps.rb, spec/controllers/taxonomy_signups_controller_spec.rb
This makes the existing checks more consistent, and adds a couple of new ones. We had some [requests over the weekend with unexpected param values](https://errbit.publishing.service.gov.uk/apps/5501a9da0da115b6b8004b79/problems/58e9474665786327ddc80b00) and it's better to not return an error response if we can avoid it.
I considered also adding a check for the [content store response being 400](https://errbit.publishing.service.gov.uk/apps/5501a9da0da115b6b8004b79/problems/58e9474765786327ed000b00) but wasn't sure if that's expected behaviour - maybe that should be fixed in content store?
=> Validate user input more thoroughly for taxonomy signups

app/views/taxonomy_signups/confirm.html.erb, app/views/taxonomy_signups/new.html.erb
This reverts commit 21a1c312332167c4ed714e4f2d2d1b7750aa5d57.
This reverts that change that leaves the link to the parent of the page the
user come in from instead of the page the user come in from.
Correct setting `is_parent_page` should get this to work as expected:
https://github.com/alphagov/static/blob/85b60d08fa2be3abf68fec3d6c9bc240d6d888a5/app/views/govuk_component/breadcrumbs.raw.html.erb#L18
=> Revert "Collapse taxonomy signup breadcrumbs on mobile"

app/views/taxonomy_signups/new.html.erb
Added meta tag to stop email alert pages from being indexed by search engines.
Trello: https://trello.com/c/s7JviEzz/131-prevent-search-indexes-indexing-email-signup-pages-on-search
=> Prevent search indexes indexing email signup pages on search

app/models/taxonomy_signup.rb, spec/models/taxonomy_signup_spec.rb
Associated taxons (those that are included within another taxon e.g. `/world/birth-death-and-marriage-abroad` that is included in all country taxons) are currently causing errors when users try to subscribe to them.
This is because, whilst they get a different slug and content id, their title within the content item stays the same. Govdelivery currently enforces a uniqueness constraint on subscription names and we use the content item title for this purpose.
Consequently, when a user tries to subscribe to an associated taxon it will fail if that title has already been used. Ideally, this constraint would be removed at Govdelivery as it seems to serve no purpose given that the subscription topics already have a unique ID there. As we are unable to make this happen currently this commit …
=> Support subscriptions to associated taxons

Gemfile, Procfile, app.json
* Heroku needs to read ruby version from Gemfile
* https://devcenter.heroku.com/articles/github-integration-review-apps
Master automatically deploys to:
http://email-alert-frontend.herokuapp.com/
PR review apps will be available at:
http://email-alert-frontend-pr-XXX.herokuapp.com/
=> Enable Heroku review apps

app/controllers/application_controller.rb, spec/controllers/taxonomy_signups_controller_spec.rb
When attempting to subscribe to a taxon that has been removed, the
`TaxonomySignupController` currently triggers a 500 because a
GdsApi::HTTPGone exception is being thrown. This commit catches
the exception in the ApplicationController and returns a 410, similar to
how it currently works with 404 responses.
=> Guard against taxon content items that are gone

lib/tasks/publishing_api.rake
Create a rake task that will allow us to publish a prefix route to Publishing Api. This allows us to create a route for `/email/unsubscribe`.
[Trello](https://trello.com/c/M0ODsZHV/398-add-prefix-route-to-router-to-point-email-to-email-alert-frontend)
Related PR in [GOV.UK Content Schemas](https://github.com/alphagov/govuk-content-schemas/pull/669)
=> Add rake task to publish unsubscribe prefix route

lib/tasks/publishing_api.rake
This commit moves the taxonomy email signup page publishing rake task from content-tagger to email-alert-frontend since it makes more sense for it to be here.
The code is currently in https://github.com/alphagov/content-tagger/blob/master/lib/tasks/taxonomy/register_email_signup_page.rake
=> Move taxonomy email signup page publishing rake task

lib/tasks/publishing_api.rake
The base path `/email-signup` was previously registered by Content Tagger.
Email Alert Frontend should be the `publishing_app` and `rendering_app` so
we need a task to force override the `publishing_app` in Publishing Api.
We can then use the tasks to register special routes for `email-signup`
and `email-signup/confirm` without them erroring.
=> Add override task for email-signup routes

app/views/unsubscriptions/confirm.html.erb, app/views/unsubscriptions/confirmed.html.erb
Add GOV.UK header component on both confirm and confirmed pages with some context and a title.
Remove the grid styling on the confirm page to bring text and button into correct alignment.
Change the submit button on the confirm page from an `input type="submit"` tag to a `button` tag to honour the GOV.UK Static Component Guide.
[Trello](https://trello.com/c/qX0rhWF8/421-add-a-little-style-to-unsubscribe-pages)
---
---
=> Update front end styling on unsubscription pages

app/controllers/unsubscriptions_controller.rb
Most GOV.UK front end services have cookies stripped by Varnish for both
request and response. Rails by default sets and `authenticity_token` on
forms to mitigate CSRF attacks. This causes an error because Rails
attempts to verify the token, but cannot because we have no sessions.
We have decided to turn off forgery protection for the confirm method,
following prior art.
We did consider disabling sessions completely, however doing so with
`Rails.application.config.session_store :disabled` does not disable the
CSRF protection checks. It does work if used in conjunction with `protect_from_forgery
with: :reset_session` does work while keeping the `authenticity_token`
in the form.
Keeping the disabling well contained in scope to only methods that need it seems like a good thing since we are …
=> Remove forgery protection from unsubscribe

Gemfile, Gemfile.lock, app/controllers/subscriptions_controller.rb, app/views/subscriptions/new.html.erb, app/views/subscriptions/show.html.erb, config/routes.rb, lib/tasks/publishing_api.rake, spec/features/subscribe_spec.rb, spec/requests/subscriptions_spec.rb
This is a very bare bones implementation of a subscription page on email-alert-frontend that we can use to replace the GovDelivery version e.g (https://public.govdelivery.com/accounts/UKGOVUK/subscriber/new?topic_id=UKGOVUK_2332)
The journey begins.. (dun, dun, darrrrr) at `/email/subscriptions/new?topic_id=UKGOVUK_2332` and entering an email address into there and submitting the form will create a subscription for the supplied 'topic'.
Currently missing:
* the form isn't built or styled by a professional
* a 404 response (or anything other than a success) from email-alert-api when fetching the subscribable isn't handled, email-alert-frontend will 500
* handling failure to actually create the subscription
... and probably lots of other things but it does give us enough to test 'end to …
=> Add subscription page

Gemfile, Gemfile.lock, app/controllers/subscriptions_controller.rb, app/views/subscriptions/new.html.erb, spec/features/subscribe_spec.rb, spec/requests/subscriptions_spec.rb
https://trello.com/c/amAa5HkV/444-handle-error-cases-for-capturing-a-users-email-address
- show an error if the user tries to submit
without an address
- show an error if the user tries to submit with
an invalid address
- preserve the address input text if the form
fails to submit
- add test coverage for other error cases, e.g.
when no subscribable exists for the topic_id
Additionally, we probably don’t want to expose the
internal database id for a subscribable in the
form, so this looks up the subscribable again from
the topic_id parameter in #create.
=> Handle error cases when creating a subscription

docs/arch/adr-001-sessions.md
We have decide to disable csrf protection on a per-method basis and revisit the decision to not use sessions until future development work on subscription management is undertaken.
[Trello](https://trello.com/c/zuvvVOmK/423-investigating-disabling-sessions-on-email-alert-frontend)
=> Add decision record for session management

app/assets/stylesheets/unsubscriptions.scss
On the /email/unsubscribe pages, the Unsubscribe button and "Is there anything wrong with this page?" text look a bit squashed. Add a `margin-bottom` to the main div to space
things out a little.
------
=> Add margin bottom to unsubscribe button

config/initializers/services.rb
Email-alert-api is getting authentication/authorisation. This commit adds a bearer token for it.
[Trello](https://trello.com/c/75sVuXhA/455-require-all-apps-to-authenticate-with-email-alert-api)
=> Add bearer token for email-alert-api

app/assets/stylesheets/application-without-elements.scss, app/controllers/subscriptions_controller.rb, app/views/subscriptions/new.html.erb, app/views/subscriptions/show.html.erb, spec/features/subscribe_spec.rb
https://trello.com/c/HSre7K10/453-style-the-mvp-email-collection-page-needed-by-jan
https://www.gov.uk/service-manual/design/question-pages#back-link
Screenshots:
=> Add back links to collection pages as per service manual

Gemfile, Gemfile.lock, spec/features/subscribe_spec.rb, spec/requests/subscriptions_spec.rb
Bump the version of GDS API Adapters to 51.1.
Add frequency param when calling `email_alert_api_creates_a_subscription` so that we properly satisfy the interface.
Supersedes https://github.com/alphagov/email-alert-frontend/pull/107
=> Bump GDS API Adapters to 51.1

Gemfile, Gemfile.lock
Reverts alphagov/email-alert-frontend#122. 
Version 12 contains a breaking change which removes the "Is there anything wrong with this page?" link from the footer. It has to be replaced with the feedback component, but that isn't ready yet. I'll upgrade this app later this week.
=> Revert "Bump slimmer from 11.1.1 to 12.0.0"

Gemfile, Gemfile.lock
We can't currently build 1.9.21 on GOV.UK infrastructure due to a
missing library.
=> Pin to older ffi 1.9.18

app/assets/stylesheets/application-without-elements.scss, app/views/subscriptions/new_frequency.html.erb
This uses a govspeak component inside the legend of the form to inherit
govspeak styles. We also apply a class to the header so that we can give
this title a bottom margin.
This also drops the second line "You can get updates about changes:" as
having this in the legend made for a confusing screenreader experience.
Before:
After:
=> Render the frequency question in a legend

Gemfile, Gemfile.lock, startup.sh
Wider context: https://github.com/alphagov/publishing-e2e-tests/pull/202
There are still some problems to resolve running the app via unicorn in
a dev environment and these may take a while to be resolved. So this
reverts this back to the previous dev experience of starting rails
server directly. This can then be switched around later if the problems
are resolved.
=> Revert app to not use foreman in startup.sh

app/controllers/subscriptions_controller.rb, spec/features/subscribe_spec.rb
This commit forces the referer to be on gov.uk by taking the non domain parts of it and adding it onto the relevant domain. This prevents referers from third-party domains showing up on the “back” link.
Trello: https://trello.com/c/BHKZj7jR/638-fix-referer-reflected-xss-vulnerability
=> Force referer to be on gov.uk

app/assets/javascripts/application.js
For: https://trello.com/c/AK6V1hHg/103-sort-out-govuktoolkit-use-in-frontend-apps-to-avoid-object-object-in-ga
In general we don't want to require all of the JS from
govuk_frontend_toolkit, because in deployed environments we'd end up
duplicating a lot of the JS that we load in from static.  However,
depending on which static layout we use we don't actually get all of
govuk_frontend_toolkit's JS, and we might want to rely on parts that
aren't delivered by static.  In these cases it's fine to require those
files, but we should be clear about what we can and can't require to
avoid someone changing the require to `//= require govuk_toolkit` in
the future.
To that end we drop a comment at the top of `application.js` around
the existing requires explaining that they are parts of …
=> Clarify which JS requires come from govuk_frontend_toolkit

app/controllers/subscriptions_controller.rb, app/controllers/unsubscriptions_controller.rb, spec/controllers/subscriptions_controller_spec.rb, spec/controllers/unsubscriptions_controller_spec.rb
This commit sets the `Cache-Control` header for all controllers that serve pages under `/email` to “private” so they don’t get cached by the CDN. This is because cookies and sessions will be enabled soon and we don’t want specific users’ pages to be cached. It also enables CSRF protection now that cookies are enabled.
Depends on https://github.com/alphagov/govuk-puppet/pull/7402
Trello: https://trello.com/c/97eS4TdI/710-sort-out-sessions-for-email-alert-frontend
=> Set Cache-Control header and allow CSRF protection

README.md, config/routes.rb, features/step_definitions/email_alert_steps.rb, features/step_definitions/taxonomy_email_alert_steps.rb, features/taxonomy_email_alerts.feature, spec/models/taxonomy_signup_spec.rb
This commit removes references to GovDelivery in the tests.
=> Remove references to GovDelivery

Gemfile, Gemfile.lock, app/controllers/taxonomy_signups_controller.rb, app/views/subscriptions/complete.html.erb, app/views/subscriptions/new_address.html.erb, app/views/subscriptions/new_frequency.html.erb, app/views/taxonomy_signups/confirm.html.erb, app/views/taxonomy_signups/new.html.erb
We're trying to standardise the way we do navigation with the contextual navigation breadcrumbs. This PR removes the breadcrumbs from the pages in favour of a consistent back-button.
cc @rubenarakelyan
=> Consistently use back buttons instead of breadcrumbs

app/views/unsubscriptions/confirm.html.erb, app/views/unsubscriptions/confirmed.html.erb, spec/controllers/unsubscriptions_controller_spec.rb
This commit tweaks the wording on the unsubscribe confirmation page to match the page before it, and also to not repeat the same wording in both the title and paragraph.
=> Tweak wording on unsubscribe confirmation page

docs/arch/adr-001-sessions.md, docs/arch/adr-002-sessions.md
This commit adds ADR 002 on session management, which supersedes ADR 001 now that sessions and cookies have been enabled for all routes under `/email`.
=> Add ADR on session management

config/initializers/assets.rb, config/initializers/govuk_publishing_components.rb
This adds the missing configuration file which sets up the title and
stylesheet for the component guide.
We are using the application-without-elements stylesheet as elements
includes resets which impacts on the component guide rendering.
Before:
After:
=> Fix component guide

app/controllers/unsubscriptions_controller.rb, app/views/subscriptions_management/index.html.erb, config/routes.rb, spec/controllers/unsubscriptions_controller_spec.rb
This takes the title from the `email-alert-api` rather than from a URL query parameter meaning that it will always be representative of the subscription.
[Trello Card](https://trello.com/c/tQznyVfV/704-remove-the-need-to-specify-a-subscriber-list-name-on-the-unsubscribe-page)
=> Take title from API

app/views/authentication/request_sign_in_token.html.erb, app/views/authentication/sign_in.html.erb, app/views/layouts/application.html.erb, app/views/subscriptions/complete.html.erb, app/views/subscriptions/new_address.html.erb, app/views/subscriptions/new_frequency.html.erb, app/views/subscriptions_management/confirm_unsubscribe_all.html.erb, app/views/subscriptions_management/index.html.erb, app/views/subscriptions_management/update_address.html.erb, app/views/subscriptions_management/update_frequency.html.erb, app/views/taxonomy_signups/new.html.erb, app/views/unsubscriptions/confirm.html.erb, app/views/unsubscriptions/confirm_already_unsubscribed.html.erb, app/views/unsubscriptions/confirmed.html.erb
This currently is set up for all pages except the email signup (https://github.com/alphagov/email-alert-frontend/blob/master/app/views/ email_alert_signups/new.html.erb). This is probably an oversight.
cc @rubenarakelyan 
https://trello.com/c/vmMXWtP7
=> Stop search engines from indexing any of the pages

app/views/authentication/sign_in.html.erb, app/views/subscriptions/new_address.html.erb, app/views/subscriptions/new_frequency.html.erb, app/views/subscriptions_management/confirm_unsubscribe_all.html.erb, app/views/subscriptions_management/update_address.html.erb, app/views/subscriptions_management/update_frequency.html.erb, app/views/unsubscriptions/confirm.html.erb
Button component recently moved from static to the components gem. This PR updates the use of the component in this app.
The version of the gem containing the button was already incremented in a previous PR.
=> Use button component from gem

app/helpers/application_helper.rb, app/views/authentication/request_sign_in_token.html.erb, app/views/authentication/sign_in.html.erb, app/views/email_alert_signups/new.html.erb, app/views/subscriptions/new_address.html.erb, app/views/subscriptions/new_frequency.html.erb, app/views/subscriptions_management/confirm_unsubscribe_all.html.erb, app/views/subscriptions_management/index.html.erb, app/views/subscriptions_management/update_address.html.erb, app/views/subscriptions_management/update_frequency.html.erb, app/views/taxonomy_signups/confirm.html.erb, app/views/taxonomy_signups/new.html.erb, app/views/unsubscriptions/confirm.html.erb, app/views/unsubscriptions/confirm_already_unsubscribed.html.erb, app/views/unsubscriptions/confirmed.html.erb, features/step_definitions/email_alert_steps.rb
The title component is moving from Static to the gem. This makes all pages use the gem-component using a helper, which cleans up the views a bit.
https://trello.com/c/EruCrkqO
=> Use title component from the gem

app/helpers/application_helper.rb, app/views/authentication/request_sign_in_token.html.erb, app/views/authentication/sign_in.html.erb, app/views/subscriptions/complete.html.erb, app/views/subscriptions/new_address.html.erb, app/views/subscriptions/new_frequency.html.erb, app/views/subscriptions_management/confirm_unsubscribe_all.html.erb, app/views/subscriptions_management/index.html.erb, app/views/subscriptions_management/update_address.html.erb, app/views/subscriptions_management/update_frequency.html.erb, app/views/unsubscriptions/confirm.html.erb, app/views/unsubscriptions/confirm_already_unsubscribed.html.erb, app/views/unsubscriptions/confirmed.html.erb, spec/controllers/unsubscriptions_controller_spec.rb
The Govspeak component has moved from Static to the gem. This switches this app to use the gem-based component.
To make the transition easier I've added a `govspeak` helper that takes a block. This cleans up the views a lot and makes it easier to read the HTML. It also makes sure that we're using Rails' HTML escaping mechanism by default, which is needed because the component will in the future no longer call `.html_safe` on the input (https://github.com/alphagov/govuk_publishing_components/pull/356). This fixes at least one (unexploitable) [XSS vulnerability in this app][1] (`@address` is add to the page unescaped).
[1]: https://github.com/alphagov/email-alert-frontend/blob/73dc8d4db0174b215fc61c42fa8ad992f2d8f6d2/app/views/authentication/request_sign_in_token.html.erb#L17 …
=> Use govspeak component from gem

app/models/taxonomy_signup.rb, spec/models/taxonomy_signup_spec.rb
Internal names are by definition internal, so we shouldn't be using
these as user visible titles for subscriptions.
The original motivation for this related to GovDelivery, which is no
longer in use.
As far as I understand, there looks to be a general issue with email
subscription lists in the email-alert-api service having a unique
constraint on the title, which will probably cause some issues with
Topic Taxonomy subscriptions as the titles of taxons are not unique.
This reverts commit 78fdf94e64f61c1f86bb91fc4aadfc5ff602aa65.
=> Revert "Support subscriptions to associated taxons"

Gemfile, Gemfile.lock, app/helpers/application_helper.rb
https://trello.com/c/BUij6N3Y/361-turn-on-bold-for-whitehall
Rich govspeak (bold) will be enabled by default.
Depends on: https://github.com/alphagov/govuk_publishing_components/pull/463
=> Remove rich govspeak

config/environments/development.rb
This means that Email Alert Frontend assets work when using the
development environment, a real host for assets.
=> Support setting asset_host in development

Gemfile, Gemfile.lock, spec/features/subscribe_spec.rb, spec/rails_helper.rb
https://trello.com/c/0QzuQFMb/415-epic-switch-app-test-suites-from-poltergeist-to-headless-chrome-using-govuktest
Removes poltergeist which is no longer actively maintained.
The test suite doesn't need a JS driver so I've modified to work with `Capybara::RackTest`
=> Remove poltergeist

app/views/taxonomy_signups/_taxon.html.erb, app/views/taxonomy_signups/new.html.erb
Many topic pages don't have descriptions, so don't assume that they
do.
=> Don't show empty descriptions for taxons

app/views/subscriptions/new_frequency.html.erb
=> Adds `govuk-!-margin-bottom-6` spacing to legend

app/controllers/taxonomy_signups_controller.rb, app/views/taxonomy_signups/new.html.erb
At least as children. This is to prevent taxons which are not ready
for people to sign up to from showing up.
=> Don't show taxons in the alpha phase

app/assets/stylesheets/application.scss, app/views/email_alert_signups/new.html.erb, app/views/subscriptions_management/index.html.erb, app/views/unsubscriptions/confirm.html.erb
This PR fixes some bits after the major layout update in #383 as follows:
- Update email sign-up title spacing and add missing paragraph class (see captures below) - a page I didn't manage to test in local dev env
- Removes redundant output for the "Unsubscribe from everything" link
- Renders back link consistently across pages (the link was rendered in one view instead of being passed to the main layout)
---
[Trello card](https://trello.com/c/Lqs4a0p4)
=> Fix frontend after clean up

app/views/taxonomy_signups/new.html.erb
Some taxons don't have descriptions and they come through as nil, which means this line fails when it tries to concatenate the string. Later on in this file we have a `<% if @taxon['description'].present? %>` so I've replicated that in this line.
=> Only show conditional if the description is present for a taxon

app/helpers/application_helper.rb, app/views/taxonomy_signups/new.html.erb, spec/features/taxonomy_alerts_spec.rb
Alpha taxons are currently being used to provide single page email subscriptions
to support Brexit content.
Pages such as [Visit Europe after Brexit](https://www.gov.uk/email-signup/?topic=/government/visit-europe-after-brexit)
are sending people to 404 pages because the generated "Back" links go to
pages that don't exist because the taxon is in alpha stage.
This is not ideal, but we need to support this in the short term.
=> Don't show links to alpha taxons

app/controllers/subscriptions_controller.rb, app/views/subscriptions/new_frequency.html.erb, spec/features/subscribe_spec.rb
Trello: https://trello.com/c/f7DWeg4q/
Adds a `default_frequency` parameter to the email alert frontend:
- If omitted (as it will be by default), nothing changes - the "immediately" option is selected as normal.
- If specified, this will override the default select option, i.e. `default_frequency=weekly` would set the selected frequency to weekly.
We want to set the default selection to 'daily' for the Business Finder.
=> Adds option for pre-selecting one of the frequency options

app/controllers/subscriptions_controller.rb, app/controllers/subscriptions_management_controller.rb, app/helpers/frequencies_helper.rb, app/views/subscriptions/complete.html.erb, app/views/subscriptions/new_address.html.erb, app/views/subscriptions/new_frequency.html.erb, app/views/subscriptions_management/index.html.erb, app/views/subscriptions_management/update_frequency.html.erb, config/locales/en.yml
Currently, there are lots of repeated strings throughout the repository, making it difficult to:
a) update the text of an option (e.g. "No more than once a day")
b) add a new frequency (e.g. fortnightly)
...as doing so would require touching multiple files and it is likely something will get missed.
This PR consolidates all of these 'magic strings' in one place - the so far unutilised `en.yml` file - and creates a `frequencies_helper.rb` file to make it easy for the view and controllers to query this information.
As well as being a general refactor PR, this PR paves the way for working on https://trello.com/c/Y1UoRnZ9, which is likely to lead to the text tweaks alluded to in a).
=> Consolidate vocabs and create FrequenciesHelper

app/controllers/subscriptions_management_controller.rb, app/helpers/frequencies_helper.rb, app/views/subscriptions/complete.html.erb, app/views/subscriptions/new_address.html.erb, app/views/subscriptions_management/index.html.erb, config/locales/en.yml
There was some weird behaviour going on where the incorrect title was sometimes being displayed.  This changes the way we're substituting the title in the I18n string and removes the `frequency_summary` method.
Trello card: https://trello.com/c/SMUHJdsO/121-fix-email-signup-confirmation-page
=> Replace frequency_summary method with calls to I18n

app/views/subscriptions_management/index.html.erb
The wrong value was being used to present the existing frequency, therefore an error was displayed to the user rather than the frequency.
Trello card: https://trello.com/c/Af6uXux3/123-bug-in-manage-your-subscriptions
=> Fix bug in 'Manage your subscriptions' page

Gemfile, Gemfile.lock, app/controllers/unsubscriptions_controller.rb, spec/controllers/unsubscriptions_controller_spec.rb
Trello card: https://trello.com/c/VlnvU2Dl
- Updates the `UnsubscriptionController` to follow this logic:
- If their latest subscription has ended already, show the "You're already unsubscribed" page.
- Else if this is their latest subscription, render a "Are you sure you want to unsubscribe?" page.
- Else, if this is not their latest subscription, but its frequency matches that of their latest subscription, then we can act on the user's intention and unsubscribe them.
- Finally, if this is an old subscription and its frequency is different to that of their latest subscription, we cannot act on their instruction to unsubscribe as it may not be what the user intended. Instead we redirect them to manage their subscription manually.
- Updates version of `gds-api-adapter`, as we need the …
=> Smarter unsubscribe logic: match old subscriptions with new ones

app/views/authentication/request_sign_in_token.html.erb, app/views/authentication/sign_in.html.erb, spec/controllers/authentication_controller_spec.rb
Trello: https://trello.com/c/RO9xS4wS
Related to: https://github.com/alphagov/email-alert-api/pull/885
From our research we know that the 'Manage your subscriptions' page is causing confusion for users trying to change their email frequency.
We should clarify the content design of this page to make clear why the user is being asked to confirm their email address, and that this will enable them to change their email frequency.
=> Add explanatory text to the 'Manage your subscriptions' page

config/locales/en.yml
Trello: https://trello.com/c/rgb9qLtB
User research showed some users were confused by what 'No more than once a day' and 'No more than once a week' subscription options meant.
This is a problem for all subscriptions across GOV.UK
The requested changes are here: https://docs.google.com/document/d/1yEMoTegE8Abm_ZF3tlhPErK_VduhnGk1l45Leak7vgo/edit
=> Make wording for daily or weekly updates clearer

app/controllers/content_item_signups_controller.rb, app/models/content_item_subscriber_list.rb, app/models/email_volume/weekly_email_volume.rb, app/views/content_item_signups/confirm.html.erb, app/views/content_item_signups/new.html.erb, spec/features/taxonomy_alerts_spec.rb, spec/models/content_item_subscriber_list_spec.rb, spec/models/weekly_email_volume_spec.rb
This commit allows the following document types - ministerial_role,
person, topical_event and word_location to be initially signed up using
email-alert-frontend.
This is needed so when we retire the whitehall email signup pages we can
redirect here.
Trello:
https://trello.com/c/tgWUR1dx/25-switch-whitehalls-email-signup-pages-to-use-email-alert-frontends
=> Add other document types to be permitted for signup

app/controllers/content_item_signups_controller.rb, spec/controllers/content_item_signups_controller_spec.rb
This taxon has been changed, but there are 500+ links to the email
signup page on GOV.UK (and possibly elsewhere online), so just
redirect the old URL for now.
This redirect should be removed when the content is updated.
---
https://govuk.zendesk.com/agent/tickets/3785368
=> Redirect /government/brexit topic to /brexit

app/controllers/development_controller.rb, app/views/development/index.html.erb, config/routes.rb
Trello: https://trello.com/c/FGYU4NlN/92-differentiate-between-your-get-ready-for-brexit-results-in-subscription-management
This gives us something other than an error for when you view this
application in a development environment - and can stop govuk-docker
assuming that the application is unavailable when you run `govuk-docker
startup` as that expects a successful response.
How it looks:
=> Create a root development page

app/helpers/application_helper.rb, app/views/authentication/request_sign_in_token.html.erb, app/views/authentication/sign_in.html.erb, app/views/subscriptions/complete.html.erb, app/views/subscriptions/new_address.html.erb, app/views/subscriptions_management/confirm_unsubscribe_all.html.erb, app/views/subscriptions_management/index.html.erb, app/views/subscriptions_management/update_address.html.erb, app/views/subscriptions_management/update_frequency.html.erb, app/views/unsubscriptions/confirm.html.erb, app/views/unsubscriptions/confirm_already_unsubscribed.html.erb, app/views/unsubscriptions/confirmed.html.erb
This application was making heavy use of the govspeak component as way
to style plain HTML. This led to confusion about whether this
application used govspeak/markdown and many cases where interface
controls had visited states that didn't quite make sense as they're
meanings may differ.
This change replaces these calls with plain classes.
=> Replace govspeak helper with classes

app/views/subscriptions_management/index.html.erb, spec/controllers/subscriptions_management_controller_spec.rb
This commit adds some extra content to the subscription management page
for each subscription, the additions are as follows:
* The time the subscription was created
* The subscriber list's desciption if present for the associated
subscription
Finally, I'm not sure about including the govspeak gem for this one use
as we need it to convert the subscriber_list description - markdown link
in this case to a html link and the actual class I'm using doesn't make
much sense in this context 'Govspeak::Document' as we aren't using a
document.
Related PR:
https://github.com/alphagov/email-alert-api/pull/977
Trello:
https://trello.com/c/FGYU4NlN/92-differentiate-between-your-get-ready-for-brexit-results-in-subscription-management
=> Add extra information for subscription management

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/assets/stylesheets/mixins/_govuk-template-link-focus-override.scss
https://trello.com/c/MRsMdjkS/72-update-email-alert-frontend-to-govukpublishingcomponents-v20-with-compatibility-mode-on
- Update gem to version 21
- Remove redundant CSS
- Switch to using design system mixins
- Add a temporary mixin to override styles from govuk-template
Due to dependencies you can't follow a full user journey through locally or on heroku so I've pushed the branch to integration. 
No screenshots as the visual differences are minimal except for the focus states.
Example starting points:
https://www.integration.publishing.service.gov.uk/email/subscriptions/new?topic_id=rail-accident-investigation-branch-raib-reports-with-the-following-railway-type-light-rail-2
https://www.integration.publishing.service.gov.uk/email-signup/confirm?link=%2Fgovernment%2Forganisations%2Fgovernm …
=> Update govuk_publishing_components to v21

spec/controllers/subscriber_authentication_controller_spec.rb, spec/controllers/subscriptions_management_controller_spec.rb
https://trello.com/c/dIAlk2dp/278-double-opt-in-create-a-subscription-before-the-success-page
Previously we had warnings about a repeated constant definition for
EMAIL_ALERT_API. This fixes the warning by using gds-api-adapters instead
of manual stub_request calls.
=> Use API adapters instead of constants

app/controllers/subscriber_authentication_controller.rb, app/controllers/subscription_authentication_controller.rb, app/models/auth_token.rb, app/views/subscription_authentication/expired.html.erb, app/views/subscriptions/complete.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/subscriber_authentication_controller_spec.rb, spec/controllers/subscription_authentication_controller_spec.rb, spec/features/subscribe_opt_in_spec.rb, spec/features/subscribe_spec.rb, spec/support/token_helper.rb
https://trello.com/c/dIAlk2dp/278-double-opt-in-create-a-subscription-before-the-success-page
This adds a new feature to create (or update) a subscription against a
validated JWT token. Since the address to subscribe to is encrypted within
the token, we can be sure the request represents genuine intent. As an
additional protection, we also validate the subscriber list matches the one
in the token, so that it can't be used out of context.
=> Add new opt-in subscribe feature

app/controllers/subscriptions_management_controller.rb, app/helpers/frequencies_helper.rb, app/views/subscriptions/complete.html.erb, app/views/subscriptions/new_address.html.erb, app/views/subscriptions_management/index.html.erb
This fixes a broken translations and switches to using I18n methods
that throw exceptions instead of silently failing, so we can catch
similar failures before they get deployed.
=> Fix and protect against missing translations

app/views/content_item_signups/confirm.html.erb
The email signup page currently says that the default frequency is "instant" emails. Following https://github.com/alphagov/email-alert-frontend/pull/624, this is no longer the case.
=> Remove mention of default frequency

app/controllers/subscriber_authentication_controller.rb, app/controllers/subscriptions_controller.rb, app/controllers/subscriptions_management_controller.rb, config/locales/subscriber_authentication.yml, config/locales/subscriptions.yml, config/locales/subscriptions_management.yml, spec/controllers/subscriber_authentication_controller_spec.rb, spec/controllers/subscriptions_controller_spec.rb, spec/controllers/subscriptions_management_controller_spec.rb
https://trello.com/c/dBwLRlDm/283-double-opt-in-send-double-opt-in-email-before-creating-subscription
This moves all string constants in controllers into locale files, which
is where we should define this kind of non-programmatic data.
=> Extract string constants out of controllers

app/controllers/subscriptions_controller.rb
Trello: https://trello.com/c/u6yXgl9h/314-remove-redundant-uses-of-defaultfrequency-parameter-on-email-signup-links
This PR relies on https://github.com/alphagov/finder-frontend/pull/1805 being merged and deployed first, so we are sure that no apps are making use of the default_frequency param.
=> Remove default frequency param

config/routes.rb
https://trello.com/c/dIAlk2dp/278-double-opt-in-create-a-subscription-before-the-success-page
Previously we scoped this route under '/manage'. This removes the
old route, which we kept for backwards compatibility. New auth emails
should now be using the scoped URL, and since after 7 days all the
emails containing the old URL are now expired, we think it's reasonable
to completely remove the old route.
=> [DO NOT MERGE] Remove legacy route to process sign in token

Gemfile, Gemfile.lock
21.15.0
Allow textarea to be described by an element outside the component (#1225)
Add guidance_id to contextual guidance component (#1225)
Update cookie banner component from an opt-out to an opt-in approach (#1227)
=> Update to version 21.15.0

app/models/auth_token.rb, spec/controllers/subscription_authentication_controller_spec.rb, spec/features/subscribe_opt_in_spec.rb, spec/models/auth_token_spec.rb, spec/support/token_helper.rb
https://trello.com/c/FwB5bALg/336-double-opt-in-fix-data-leak
Previously we supported verification of a subscriber via the signature
of a JWT token, for which the payload isn't encrypted. This adds support
for an encrypted+signed token using ActiveSupport's MessageVerifier.
We expect to switch all tokens to use this new mechanism and remove
support for JWT tokens after about a week from deployment, since the
tokens would be invalid anyway after that time.
Since the associated secret is only intended for this purpose, we use a
fixed, empty salt ("") when generating a key of the appropriate length
for the MessageVerifier.
=> Support encrypted tokens (with JWT fallback)

spec/features/change_email_address_spec.rb, spec/features/change_email_frequency_spec.rb, spec/features/manage_subscriptions_confirmation_email_spec.rb, spec/features/unsubscribe_all_spec.rb, spec/features/unsubscribe_spec.rb
https://trello.com/c/wb8hyN7U/308-double-opt-in-add-feature-tests-for-managing-subscriptions
=> Add feature tests for managing subscriptions

app/controllers/subscriptions_management_controller.rb, app/views/subscriber_authentication/request_sign_in_token.html.erb, app/views/subscriber_authentication/sign_in.html.erb, app/views/subscriptions_management/confirm_unsubscribe_all.html.erb, app/views/subscriptions_management/index.html.erb, app/views/subscriptions_management/update_address.html.erb, app/views/subscriptions_management/update_frequency.html.erb, app/views/unsubscriptions/_confirmation.html.erb, app/views/unsubscriptions/confirm.html.erb, app/views/unsubscriptions/confirm_already_unsubscribed.html.erb, app/views/unsubscriptions/confirmed.html.erb, config/locales/subscriber_authentication.yml, config/locales/subscriptions_management.yml, config/locales/unsubscriptions.yml, spec/controllers/subscriptions_management_controller_spec.rb, spec/controllers/unsubscriptions_controller_spec.rb, spec/features/change_email_address_spec.rb, spec/features/change_email_frequency_spec.rb, spec/features/manage_subscriptions_confirmation_email_spec.rb, spec/features/unsubscribe_all_spec.rb, spec/features/unsubscribe_spec.rb
For https://trello.com/c/wb8hyN7U/308-double-opt-in-add-feature-tests-for-managing-subscriptions
=> Extract translations for subscriptions management and subscriber authentication

app/models/auth_token.rb, spec/controllers/subscriber_authentication_controller_spec.rb, spec/features/change_email_address_spec.rb, spec/features/change_email_frequency_spec.rb, spec/features/unsubscribe_all_spec.rb, spec/models/auth_token_spec.rb, spec/support/token_helper.rb
https://trello.com/c/FwB5bALg/336-double-opt-in-fix-data-leak
This removes support for auth tokens created using JWT. After a period
of dual running, we now expect users to only click links with the new
tokens created using Rails' MessageEncryptor.
=> Drop support for JWT tokens

app/controllers/subscriptions_controller.rb, app/views/subscription_authentication/complete.html.erb, app/views/subscriptions/check_email.html.erb, app/views/subscriptions/new_address.html.erb, app/views/subscriptions/new_frequency.html.erb, config/locales/subscription_authentication.yml, config/locales/subscriptions.yml, spec/features/subscribe_back_spec.rb, spec/features/subscribe_opt_in_spec.rb, spec/features/subscribe_spec.rb
Some last minute improvements to the UI.
https://trello.com/c/umMOCXZa/328-double-opt-in-implement-last-few-cosmetic-content-updates
=> Several UI improvements

app/controllers/content_item_signups_controller.rb, spec/controllers/content_item_signups_controller_spec.rb
Sometimes taxa are moved and a redirect is set in place.  Email signup links to the moved taxons are often hardcoded in content and will have to be updated. Some may be missed resulting
in broken links.
Previously, the case of redirecting /government/brexit -> /brexit was handled
as a special hard coded case.
This PR makes makes this more general by following the redirects in
the content item.
trello: https://trello.com/c/zhg0rOFS/386-update-government-brexit-redirect-in-email-alert-frontend
=> Follow redirects for content item email signups

app/views/subscriptions_management/update_address.html.erb
- this appears to be the only element in all of GOV.UK still using the 'column-two-thirds' class from static, despite being surrounded by the newer govuk-grid-column classes
- I assume this was missed during the last update
- removing as it's already inside a two-thirds column and this class is going to be removed
=> Remove grid class

Rakefile, script/cucumber
This is depended on by https://github.com/alphagov/govuk-jenkinslib/pull/66.
=> Make entire repository pass Rubocop linting

config/locales/subscriber_authentication.yml
We're thinking of adding a higher priority queue for these emails but, until that is done, just tell people that there's a delay.
=> Add note about email auth delay

config/locales/unsubscriptions.yml
In the event that the email queues are long it may take some time for unsubcriptions to work. This lets the user know that.
Trello - https://trello.com/c/eeMr0zaf/864-content-changes-to-email-unsubscribe-page
=> Make it clear that it may take time for unsubscriptions to take effect

config/locales/subscriber_authentication.yml
We have some evidence that people are confused by having to "confirm" their email address when they already had to do that to sign up in the first place.
=> Make it clear that the email is to manage subscriptions

app/controllers/content_item_signups_controller.rb, app/models/content_item_subscriber_list.rb, spec/models/content_item_subscriber_list_spec.rb
Originally this PR -> https://github.com/alphagov/email-alert-frontend/pull/546 was merged
which enabled more document types to signup via email-alert-frontend...
great! But as it turns out this broke email signups for new users
signing up to world locations (taxon and news) as taxon world location
were now using the links key world_locations which didn't match to any
content-changes coming in as they were expecting taxon_tree and news
world locations broke because the content-id being saved in the
subscriber list was the taxon world location instead of the one known
about in whitehall (news).
This PR reverts this change so all world location email signups should
now work as expected going forward.
Related to:
https://github.com/alphagov/whitehall/pull/5464
Trello: …
=> [DNM] Revert world location signups

app/helpers/frequencies_helper.rb, app/views/subscriptions/new_frequency.html.erb, spec/helpers/frequencies_helper_spec.rb
This adds the ability to set default frequency options for particular topic ids. Also adds the default checked option of daily for the `coronavirus-covid-19-uk-government-response` topic id
=> Add default frequency options for topic ids

app/controllers/content_item_signups_controller.rb, app/views/content_item_signups/confirm.html.erb, app/views/content_item_signups/new.html.erb, spec/features/topic_signup_back_spec.rb
Trello: https://trello.com/c/xV0rgaXK/44-spike-removing-the-first-page-of-coronavirus-email-subscription-journey
In the email sign-up journey, go straight to 'confirm' if there are no subscription options (like topics or child-taxons) to choose from.
The 'new' and 'confirm' view are very similar when there are no options to choose from (see screenshots below). This just means more clicks for users.
=> Skip 'options' page in email subscription journey if there are no options to choose from

app/controllers/content_item_signups_controller.rb, app/views/content_item_signups/confirm.html.erb, app/views/subscriptions/new_frequency.html.erb, app/views/subscriptions_management/update_frequency.html.erb, config/locales/frequencies.yml, config/locales/subscriptions.yml, spec/features/content_item_signup_spec.rb, spec/helpers/frequencies_helper_spec.rb
https://trello.com/c/7iBwU6g4/59-update-the-content-for-the-coronavirus-covid-19-uk-government-response-email-subscription-sign-up
=> Email subscription sign up content updates

app/controllers/content_item_signups_controller.rb, app/models/email_volume/organisation_weekly_email_volume.rb, app/models/email_volume/taxon_weekly_email_volume.rb, app/models/email_volume/topical_event_weekly_email_volume.rb, app/models/email_volume/weekly_email_volume.rb, app/views/content_item_signups/confirm.html.erb, spec/features/content_item_signup_spec.rb, spec/models/weekly_email_volume_spec.rb
This sets expectation for the weekly volume of changes for the coronavirus topic.
The implementation is somewhat hacky. However, the plan is to migrate the coronavirus topical event to a taxon, which means the hack will be removed then.
https://trello.com/c/1TbLyQXY/73-display-estimated-weekly-email-volume-for-coronavirus-email-sign-up
=> Add coronavirus weekly email volume

app/presenters/content_item_subscription_presenter.rb, app/views/content_item_signups/confirm.html.erb
Trello: https://trello.com/c/x2QeWfip/61-rename-coronavirus-email-subscription-title
Temporarily override the Coronavirus topical event title for the email signup journey.
We added a [migration task to rename the email subscriber list title itself](https://github.com/alphagov/email-alert-api/pull/1199), but this isn't used in the email alert frontend when someone is signing up. Instead, this relies on the content_item of (in this case) the topical event. 
We could rename the topical event itself in Whitehall but this is may need more discussion with content designers and more broadcasting of the change. Let's add a quick override here and remove it once the product team have switched to the new taxonomy.
=> Override topical event title for email

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/views/sessions/invalid.html.erb, config/locales/sessions.yml, spec/controllers/application_controller_spec.rb
Previously we were showing users the default rails 422 pages on InvalidAuthenticityToken exceptions. This adds a GOV.UK styled error page, thats should be less confusing and tell the users to try the form again.
=> Add error page for invalid sessions

app/controllers/subscriptions_management_controller.rb, app/controllers/unsubscriptions_controller.rb, app/views/subscriptions_management/index.html.erb, config/locales/subscriptions_management.yml, config/locales/unsubscriptions.yml, spec/controllers/subscriptions_management_controller_spec.rb, spec/controllers/unsubscriptions_controller_spec.rb, spec/features/unsubscribe_all_spec.rb
This PR updates the content for the _unsubscribe_ journey.
The content changes aim to:
* set user expectations
* provide useful information at the most appropriate point in the journey
* improve the consistency of content elsewhere in the email notifications service
=> Update unsubscribe content

app/views/subscriber_authentication/request_sign_in_token.html.erb, app/views/subscriber_authentication/sign_in.html.erb, config/locales/subscriber_authentication.yml
This PR updates the content for the _Manage your subscriptions_ journey.
The content changes aim to:
* set user expectations
* provide useful information at the most appropriate point in the journey
* improve the consistency of content elsewhere in the email notifications service
=> Update 'manage your subscriptions' content

app/views/subscriber_authentication/sign_in.html.erb, app/views/subscriptions/new_address.html.erb
Trello card: https://trello.com/c/qIJ76Y37
At two points in the email journey we ask people to enter their email address, and perform client-side validation on this using HTML form validation, something that browsers have built-in support for.
However, this kind of validation is not recommended. We already do our own validation checks, so we should turn off the validation by using the `novalidate` attribute on our form elements.
The Design System team advise against using HTML form validation. Their recommendation is to use server-side validation, and only add custom client-side validation if there is a real need for it.
=> Set "novalidate" attribute on forms

app/presenters/content_item_subscription_presenter.rb, spec/unit/presenters/content_item_subscription_presenter_spec.rb
Currently, when taxon description is empty, the prefix "This will include:" is displayed. This makes sure we don't.
We are implementing this fix until we can find a longer-term solution for what is a somewhat flawed behaviour.
To cite @benthorner:
> Example of how this doesn't make sense: https://www.gov.uk/email-signup/?topic=/education/education-in-prisons
> Example of how showing the description at all is a bit questionable: https://www.gov.uk/email-signup?link=/government/organisations/government-digital-service
> Perhaps we just want to ditch the description entirely?
---
https://trello.com/c/V2xPGN2t/246-fix-this-will-include-when-taxon-description-is-empty
=> Show no description for taxon when it has none

app/assets/stylesheets/application.scss
While implementing some web performance monitoring I noticed that we are downloading both v1 and v2 fonts for pages using this app. I believe this is because we are missing `$govuk-compatibility-govuktemplate: true;`
This PR should hopefully stop the v2 fonts and bring the weight down to 120KB instead of 184KB. Full WebPageTest results can be seen [here](https://www.webpagetest.org/result/200514_K2_aa4405c1178f4d924eb69ae51a83f9e4/1/details/#waterfall_view_step1)
=> Add govuk-compatibility-govuktemplate to remove font duplication.

Rakefile
This is currently causing deploy failures.
=> Fix clearing non-existant 'default' task

spec/controllers/unsubscriptions_controller_spec.rb
These methods are due to be removed in https://github.com/alphagov/gds-api-adapters/pull/995
I noticed when removing them that email_alert_api methods weren't set up
correctly to warn so these likely got missed on any previous fixes.
=> Remove deprecated GdsApiAdapter stub methods

app/views/content_item_signups/new.html.erb
Trello: https://trello.com/c/55FokrdD/300-update-how-we-describe-sub-topics-on-the-taxon-selector-page
Change "or one of the following [x] topics" to "or one of the following [x] sub-topics"
It makes things clearer and also more consistent with how we refer to them on [search filters](https://www.gov.uk/search/research-and-statistics)
=> Change topic to sub-topic

app/controllers/content_item_signups_controller.rb, app/models/content_item_subscriber_list.rb, spec/models/content_item_subscriber_list_spec.rb
https://trello.com/c/KNWv9Dgx/258-not-ready-to-start-deprecate-and-remove-legacy-email-signup-pages
Previously these relied on the 'email_alert_signup' functionality in this
app, which we'd like to remove, since most formats now use the generic
'content_item_signup' functionality. This adds support for creating
subscriptions based on the content item.
Please see the commits for more details.
=> Support content item signup for service manual

config/application.rb, config/environments/development.rb, config/environments/production.rb, config/initializers/assets.rb
Trello: https://trello.com/c/oNEtjIVp/99-serve-static-assets-from-www-hostname
This allows asset host to be set by ASSET_HOST env var rather than
GOVUK_ASSET_HOST. This is in preparation for the assets of this app
changing hostname from assets.publishing.service.gov.uk to www.gov.uk.
As part of this change the path to assets is changed to
/assets/email-alert-frontend
The expectation is that this env var will only be set in dev
environments when proxying isn't set up for router.
=> Serve assets from www hostname

app/views/content_item_signups/new.html.erb, spec/features/content_item_signup_spec.rb
Trello: https://trello.com/c/XxMJ77lG/302-add-default-to-taxon-selection-page
Preselect the parent taxon on the taxonomy email sign-up page.
This used to be the behaviour but it was removed which meant someone trying to click through the journey without any topic selected was being redirected to the GOV.UK homepage - a confusing/jarring thing to happen for a user.
**Note: other scenarios will still redirect to the homepage - this PR does not address that. That is addressed in a separate PR https://github.com/alphagov/email-alert-frontend/pull/812**
=> Select parent taxon by default

app/controllers/application_controller.rb, app/controllers/content_item_signups_controller.rb, spec/controllers/content_item_signups_controller_spec.rb
Related to https://trello.com/c/XxMJ77lG/302-add-default-to-taxon-selection-page and https://github.com/alphagov/email-alert-frontend/pull/811
Removes the code which redirects a user to the GOV.UK homepage if something goes wrong with email signup and instead raises a 400 Bad Request error.
Summary:
| Scenario | Previous Behaviour | New Behaviour | Example |
| --- | --- | --- | --- |
| New (invalid topic) | redirect to / | returns 400 | /email-signup/?topic=123 |
| New (missing topic) | redirect to / | returns 400 | /email-signup |
| New (not a taxon) | redirect to / | returns 400 | /email-signup/?topic=/cma-cases |
| Confirm (invalid topic) | redirect to / | returns 400 | /email-signup/confirm?utf8=%E2%9C%93&topic=123 |
| Confirm (missing topic) | redirect to / | returns 400 | …
=> Remove homepage redirect

app/helpers/frequencies_helper.rb, app/views/subscriptions/new_frequency.html.erb, spec/helpers/frequencies_helper_spec.rb
When users get to the frequency select page of the coronavirus taxon sign up page (https://www.gov.uk/email/subscriptions/new?topic_id=coronavirus-covid-19) the default should be set as daily digest.
It's our biggest subscription list (~300,000). Lots of content is being tagged with it and each of these triggers a notification if on immediate alerts. On busy days it's both a lot of emails to send and a lot of emails to receive.
https://trello.com/c/5TZstRq7/317-coronavirus-taxon-sign-up-set-default-to-the-daily-digest
=> Default coronavirus email frequency to daily

app/models/email_volume/taxon_weekly_email_volume.rb, spec/models/weekly_email_volume_spec.rb
The only taxon we are getting extreme volumes for are notifications
for content tagged with the Coronavirus taxon. We want to inform
the user what these numbers are, so that they can get decide whether
they still want to get immediate notifications. The min value is
based on a daily average, and the maximum is on a day's maximum
content changes during the first couple of weeks of the taxon's
existence.
https://trello.com/c/rcC3U4Ah
=> Add extreme EmailVolume value

app/services/verify_subscriber_email_service.rb, app/services/verify_subscription_email_service.rb
https://trello.com/c/fCrWTqFj/372-incident-action-rate-limit-email-authentication-emails-by-address
=> Harden rate limits for verification emails

README.md
https://trello.com/c/KNWv9Dgx/258-migrate-legacy-email-signup-pages-for-service-manual-formats
Migrated in: https://github.com/alphagov/service-manual-publisher/pull/812
=> Remove service manual from legacy signup list

app/controllers/application_controller.rb, spec/controllers/content_item_signups_controller_spec.rb
Trello: https://trello.com/c/koo6gJov/355-increase-visibility-of-sentry-alerts-for-email-apps-and-services
In our Sentry error log there are numerous errors raised when clients
have tried to put in dubious strings in a query string which have then
been forwarded to internal Rails APIs [1].
These dubious query strings can result in the downstream Rails APIs
returning a 400 bad request response. It seems appropriate to then
return this to user.
One thing to note is that this will catch all other 4xx responses (such
as 422 or 401) that are not configured with their own exception
handlers. This doesn't seem too big a semantic problem since they are
types of bad request so meet the semantics. Were this to become a
problem we would want to expand GdsApiAdapters to have a dedicated …
=> Rescue GdsApi::HTTPClientError and return bad request

app/controllers/subscriptions_controller.rb, app/views/content_item_signups/confirm.html.erb, app/views/content_item_signups/new.html.erb, app/views/subscriptions/new_address.html.erb, app/views/subscriptions/new_frequency.html.erb, app/views/subscriptions_management/update_frequency.html.erb
Page titles of pages within the journey to subscribe to email alerts are problematic.
When starting from https://www.gov.uk/world/switzerland the first three pages all have the same page title: "UK help and services in Switzerland". The page title does not accurately reflect what the [second](https://www.gov.uk/email-signup?link=/world/switzerland) and [third](https://www.gov.uk/email-signup/confirm?utf8=%E2%9C%93&topic=%2Fworld%2Fswitzerland) pages are about.
The [fourth page](https://www.gov.uk/email/subscriptions/new?topic_id=uk-help-and-services-in-switzerland-24e8ef8275) has the page title "Get emails when pages are added or updated" which describe the whole journey but not the single page, while the [fifth page](https://www.gov.uk/email/subscriptions/new?frequency=daily&topic_id=uk-h …
=> Amend email alerts misleading/vague page titles

app/views/content_item_signups/new.html.erb, app/views/subscriptions/new_frequency.html.erb, app/views/subscriptions_management/update_frequency.html.erb
Moves captions for radio button collections into the the legend for that radio button fieldset.
Currently these captions exist outside the fieldset legends as styled p tags. This makes the caption for the radio fieldset not programatically determinable, failing WCAG SC 4.1.2. By moving it into the legend associated with the radio fieldset it clearly associates that caption with the radio buttons and allows us to make more efficient use of the components gem radio buttons API.
**Card:** https://trello.com/c/Np871Jwm/335-email-alerts-missing-legend
=> Move radio button captions into legends for those radio button fieldsets

Gemfile, Gemfile.lock, app/models/auth_token.rb, spec/support/token_helper.rb
These are the changes necessary for Ruby 2.7.1
I've left the Ruby version as 2.6.6 since there's an automatic script to change all the apps' Ruby versions at once.
Couple of deprecation warnings coming from GDS API Adapters, which are addressed in this PR https://github.com/alphagov/gds-api-adapters/pull/1003
=> Upgrade to ruby 2.7.1

app/views/subscriptions/new_address.html.erb
Adds `autocomplete="email"` to the input component for collecting a user's email address for the new subscription view.
Input fields that don't include the appropriate autocomplete attribute values vail WCAG SC 1.3.5.
No visual changes.
**Card:** https://trello.com/c/jmQAcEG3/371-email-alerts-missing-autocomplete-attribute
=> Add email autocomplete to new subscription view

app/models/email_alert_signup.rb, app/views/email_alert_signups/new.html.erb
https://trello.com/c/233ZtYfR/504-design-how-to-discourage-new-subscriptions-for-individual-emails
Previously we used to show a bunch of links on the initial page for
a '/government/*/email-signup' type subscription. Since only travel
advice still uses the '*/email-signup' workflow [1], we can safely
delete this untested and unused feature.
Removing this now will simplify our upcoming work around revamping
the signup pages; it's an unnecessary complication.
[1]: https://github.com/alphagov/email-alert-frontend#signup
=> Remove redundant government navigation

app/views/layouts/application.html.erb
Adds `id="content"` to the `main` element.
Currently, the skip link on email signup pages doesn't work as it's looking for an id with the name `content` which doesn't exist. Ideally, this would be fixed at the static level, however this PR solves the problem for users now, which is arguably more important for the moment.
No visual changes.
**Card:** https://trello.com/c/4Q0ZZleC/428-broken-skip-link
=> Add an id of "content" to the main element

app/assets/stylesheets/application.scss
This frontend app still had the legacy colours enabled; this should turn them off and enable the new colours. This will make this app consistent with the rest of GOV.UK.
=> Turn on new colours

app/views/subscriptions_management/index.html.erb
The GOV.UK Components gem will soon release a breaking change (https://github.com/alphagov/govuk_publishing_components/pull/1632) that will mean that:
```erb
<%= render "govuk_publishing_components/components/govspeak", {
content: sanitize("<p>This is some body text with <a href=#>a link</a></p>")
} %>
```
will raise an error.
Changing it to:
```erb
<%= render "govuk_publishing_components/components/govspeak" do %>
<%= sanitize(some_html_in_a_variable_from_elsewhere) %>
<% end %>
```
gives the same results and won't break things.
=> Updating Govspeak to use `do` block

app/views/subscriptions/new_frequency.html.erb
Updating page so it includes a `h1`, also updating `README` so startup is clearer
[Ticket](https://trello.com/c/12elBDh4)
[There is no h1 on this page](https://www.gov.uk/email/subscriptions/new?topic_id=uk-help-and-services-in-switzerland-24e8ef8275). The main content starts with an h2.
Not a strict WCAG fail, screen reader users might find it more difficult to get to the main content and understand the structure of the page. 
Before:
After:
Can view via this local URL
`http://email-alert-frontend.dev.gov.uk/email/subscriptions/new?topic_id=uk-help-and-services-in-switzerland`
The README has also been updated to include some clearer startup guidance (I ran into some problems: the docker `--live` flag is essential for this repo, this wasn't clear to me as I ran into errors spinning this …
=> Add missing h1

app/assets/stylesheets/application.scss, app/controllers/subscriptions_controller.rb, app/views/subscriptions/check_email.html.erb, app/views/subscriptions/new_address.html.erb, app/views/subscriptions/new_frequency.html.erb, config/locales/frequencies.yml, config/locales/subscriptions.yml, spec/features/subscribe_back_spec.rb, spec/features/subscribe_spec.rb
https://trello.com/c/mk5M2aKD/619-general-design-and-stylistic-updates-to-signup-workflow
This updates the pages that are common to all new subscription flows
with a new design. Please see the commits for more details.
One general theme is that I've used 'target="_blank"' for all links.
While the design didn't specify either way, most of the links seem to
be providing additional information, where it would not make sense for
the user to navigate away.
=> Update common pages for new subscriptions

app/views/development/index.html.erb
https://trello.com/c/mk5M2aKD/619-general-design-and-stylistic-updates-to-signup-workflow
Since a developer may not think to spin up the app in order to
learn about it, we should favour having documentation in the
README, which happens to already cover all of the content here.
On the other hand, keeping this page still provides a nicer
experience for someone who's new to the app. This replaces the
previous content with some simple links to further info.
=> Rewrite content for development homepage

app/controllers/content_item_signups_controller.rb, app/models/content_item_subscriber_list.rb, app/services/generate_subscriber_list_params_service.rb, spec/controllers/content_item_signups_controller_spec.rb, spec/features/content_item_signup_spec.rb, spec/models/content_item_subscriber_list_spec.rb, spec/services/generate_subscriber_list_params_service_spec.rb
https://trello.com/c/mk5M2aKD/619-general-design-and-stylistic-updates-to-signup-workflow
Fixes: https://github.com/alphagov/email-alert-frontend/issues/913
This PR makes a few changes to the the request handling:
- Use list "slug" instead of "subscription_url" for redirects
- Stop redirecting to "gov.uk" for blank redirect content items
I've also done a bit of refactoring, with the final part -
the controller tests - saved for a later PR, due to the
need to add some missing API test helpers first.
=> Simplify request handling for content item signups

config/locales/subscriptions.yml
Adds `govuk-link` classes to use the new styling and focus states and removes `target="blank"` as we don't seem to have a strong reason for using it.
Thanks @vanitabarrett for reporting this!
=> Update links defined in yml

app/controllers/application_controller.rb, app/controllers/unsubscriptions_controller.rb, app/views/unsubscriptions/confirm.html.erb, config/locales/subscriptions_management.yml, spec/controllers/application_controller_spec.rb, spec/controllers/subscriber_authentication_controller_spec.rb, spec/controllers/subscription_authentication_controller_spec.rb, spec/controllers/subscriptions_controller_spec.rb, spec/controllers/subscriptions_management_controller_spec.rb, spec/controllers/unsubscriptions_controller_spec.rb, spec/features/unsubscribe_spec.rb, spec/support/session_helper.rb
https://trello.com/c/sgJIkObA/662-authenticate-before-unsubscribing-from-digest-emails
This simplifies the existing unsubscribe controller and associated
tests, so that it's easier to add more code: we want to require the
user is authenticated in some way, in order to prove they own the
subscription they are unsubscribing from.
This PR makes a couple of minor behavioural changes:
- We always redirect to the latest subscription, irrespective of frequency.
- We always show/redirect appropriately if the user is signed in.
I decided to cut this PR here, since the volume of change is already
quite large. Please see the commits for more details.
=> Prepare to require authentication for unsubscribe

app/controllers/subscriber_authentication_controller.rb, spec/controllers/subscriber_authentication_controller_spec.rb
https://trello.com/c/sgJIkObA/662-authenticate-before-unsubscribing-from-digest-emails
This isn't tested, and isn't used in practice: we always take the
user to their list of subscriptions.
=> Remove support for redirecting after sign in

config/application.rb, config/routes.rb, lib/healthchecks/redis_connection.rb, spec/lib/healthchecks/redis_connection_spec.rb
This adds some added functionality to the healthcheck for
email-alert-frontend to enable CD.
As per the requirement for CD: 'It has a test that checks for
connectivity to any read/write dependencies'. The only DB
email-alert-frontend uses is Redis during [rate limiting]. Opening a
Redis connection and then adding, fetching and deleting a key value pair
before closing the collection seems a sufficient test for Redis
connectivity.
[rate limiting]: https://github.com/alphagov/email-alert-frontend/blob/a32156a677f3989623faf6953de6aa4c8e073e29/app/services/verify_subscriber_email_service.rb#L52
=> Add Redis connection healthcheck

.github/pull_request_template.md
We will soon make email-alert-frontend continuously deployed so this
adds some guidance around the process to the PRs.
Dependant on:
=> Add pull request template for email-alert-frontend

app/controllers/unsubscriptions_controller.rb, app/views/unsubscriptions/confirm.html.erb, spec/controllers/unsubscriptions_controller_spec.rb, spec/features/unsubscribe_spec.rb
https://trello.com/c/sgJIkObA/662-authenticate-before-unsubscribing-from-digest-emails
Please see the commits for more details. Note that the approach
changes in the final commit, as I realised the original way had
a flaw in it. Hopefully the story is easy to follow, but I can
try to rewrite the branch if not.
=> Require some kind of authentication to unsubscribe

app/services/generate_subscriber_list_params_service.rb, spec/services/generate_subscriber_list_params_service_spec.rb
https://trello.com/c/3H67DU88/456-epic-record-the-origin-of-all-subscriber-lists-on-govuk
The URL property of subscriber lists was introduced to support the
Brexit Checker [1], but the functionality applies to all lists. We
think that recording these URLs will in future help us to determine
which lists are still "alive", by checking they refer to a live URL
on GOV.UK. This takes a step in that direction.
[1]: https://github.com/alphagov/finder-frontend/blob/2b565b6ccb6449d329dba00bb39d4d629a42c81a/app/controllers/brexit_checker_controller.rb#L189
=> Record the origin of new content item-based lists

app/views/subscriptions_management/index.html.erb, spec/controllers/subscriptions_management_controller_spec.rb
https://trello.com/c/gbYVX8lK/690-send-users-a-link-to-their-results-as-part-of-subscribing-to-the-checker
Previously we relied on the list description being a markdown URL
for Brexit Checker results. However, we want to move away from a
freeform description in the API because:
- It's only used for Brexit Checker lists.
- It's freeform, so we can't track the links (in emails).
- The description is repetitive and inaccurate (really a URL).
This replaces the description with the same text, but hard-coded,
which makes it easier to replace, clearer in purpose, and (thus)
easier to target for deletion in the future.
=> Replace list description with hard-coded text

app/models/email_alert_signup.rb, spec/features/email_alert_signup_spec.rb, spec/models/email_alert_signup_spec.rb
This removes support for a couple of fields:
- govdelivery_title on email_alert_signup content items
- subscription_url for subscriber lists
In the former case, we can also update the schema to mark
this field as unused e.g. by removing it.
Please see the commits for more details.
=> Remove support for unused fields

Gemfile.lock, spec/controllers/subscription_authentication_controller_spec.rb, spec/features/subscribe_opt_in_spec.rb
https://trello.com/c/hdOrNhuC/669-sign-in-after-subscribing
This matches the new interface for the helper [1].
[1]: https://github.com/alphagov/gds-api-adapters/blob/4ad9b70a4e06b65268a8128a5b5842ffa461575a/lib/gds_api/test_helpers/email_alert_api.rb#L221-L228
=> Bump GDS API Adapters and fix test stubs

spec/features/email_alert_signup_spec.rb
Previously we switched to using travel advice content item examples
[1], as these are the only remaining users of the email_alert_signup
schema. Raising the PR to remove the "policy" examples from GOV.UK
Content Schemas [2] highlighted this usage as one that was missed.
[1]: https://github.com/alphagov/email-alert-frontend/pull/946/commits/f92828d8cbe6a8149566cee343c6738d5d2a4e04#diff-4caeb9a462fa907750b801ea20af71116356e3bc655b4cc7cd07a846cdde559fL6
[2]: https://github.com/alphagov/govuk-content-schemas/pull/1033
=> Fix email signup feature to use realistic content

app/views/subscriptions_management/index.html.erb, spec/controllers/subscriptions_management_controller_spec.rb
Previously we adopted this hack in favour of manually specifying a
fake "description" for each subscriber list [1]. However, we forgot
that the URL for checker results has changed. This fixes the hack
to cope with both versions of the checker results URL.
[1]: 65f6e09
=> Fix not showing link to some checker results

.github/dependabot.yml, .gitignore, Gemfile, Gemfile.lock, Jenkinsfile, Rakefile, app/assets/javascripts/modules/track-email-alert-signup-choices.js, app/assets/stylesheets/mixins/_govuk-template-link-focus-override.scss, lib/tasks/lint.rake, package.json, spec/javascripts/modules/track-email-alert-signup-choices.spec.js, yarn.lock
Trello: https://trello.com/c/MeG1zc2m/195-roll-out-stylelint-config-gds-across-govuk
This project previously had Standard for JS linting and no Sass linting. To bring this into convention with other GOV.UK applications it adds Standardx for JS linting and Stylelint for Sass linting.
More info in the commits...
=> Use Stylelint to lint Sass and Standardx to lint JS

app/views/subscriptions/new_address.html.erb, app/views/subscriptions/new_frequency.html.erb, config/locales/subscriptions.yml
https://trello.com/c/oYRFCtBm/668-iterate-error-content-and-behaviour-for-new-signup-workflow
This synchronises the copy shown in the flash message with that on
the radio buttons / input box.
=> Update copy for errors on signup

app/controllers/content_item_signups_controller.rb, app/helpers/taxons_helper.rb, app/views/content_item_signups/taxon.html.erb, config/locales/content_item_signups.yml, spec/controllers/content_item_signups_controller_spec.rb, spec/features/content_item_signup_spec.rb
https://trello.com/c/oYRFCtBm/668-iterate-error-content-and-behaviour-for-new-signup-workflow
This also starts to move towards using the "link" query param for email
signup. Please see the commits for more details.
=> Require user to select taxon or a child taxon

README.md, app/assets/stylesheets/application.scss, app/views/content_item_signups/confirm.html.erb, app/views/content_item_signups/taxon.html.erb, app/views/email_alert_signups/new.html.erb, app/views/subscriber_authentication/request_sign_in_token.html.erb, app/views/subscriber_authentication/sign_in.html.erb, app/views/subscriptions/check_email.html.erb, app/views/subscriptions/new_address.html.erb, app/views/subscriptions_management/confirm_unsubscribe_all.html.erb, app/views/subscriptions_management/index.html.erb, app/views/subscriptions_management/update_address.html.erb, app/views/subscriptions_management/update_frequency.html.erb, app/views/unsubscriptions/confirm.html.erb, app/views/unsubscriptions/confirm_already_unsubscribed.html.erb, app/views/unsubscriptions/confirmed.html.erb
Updating headings to use [component gem](https://components.publishing.service.gov.uk/component-guide/heading)
As part of on-going work to update Frontend apps inline with component gem architecture, improves a11y, consistency & allows changes to be cascaded across all apps. ([ticket](https://trello.com/c/JlKrHDdn))
No visual changes, Design maintained.
Example links impacted:
https://www.gov.uk/email-signup/confirm?topic=%2Fmoney%2Fexpenses-employee-benefits
https://www.gov.uk/foreign-travel-advice/canada/email-signup
https://www.gov.uk/email/subscriptions/verify
https://www.gov.uk/email/manage
https://www.gov.uk/email/manage/authenticate
https://www.gov.uk/email/manage/unsubscribe-all
https://www.gov.uk/email/manage/address
`README` broken link updated + link to docs explaining how to …
=> Update to heading component

config/locales/subscriptions_management.yml
https://trello.com/c/l2cC0fY4/678-update-sign-in-journey-email-screens-to-match-design
This is to be consistent with the CTA used prior to logging in.
Before | After
-------|-----
=> Update title of manage subscriptions page

app/views/content_item_signups/confirm.html.erb, app/views/subscriptions/new_address.html.erb
Switch from using `trackClick` script to `gemTrackClick` script. They are virtually the same, the latter being [copied over from `static` to `govuk_publishing_components`](https://github.com/alphagov/govuk_publishing_components/pull/1751).
Part of [a bigger piece of work](https://github.com/alphagov/static/pull/2405) to reduce the size of assets served to users and keep our codebase to a minimum.
=> Switch from trackClick to gemTrackClick script

app/views/subscriptions/new_frequency.html.erb
~🙅🏻‍♀️ Do not merge, depends on alphagov/govuk_publishing_components#2051 🙅🏻‍♀️~
(now up to date with the latest gem changes)
The email frequency page uses a [radio component](https://components.publishing.service.gov.uk/component-guide/radio) with the `is_page_heading` parameter. 
Changes are being made to remove the `is_page_heading` parameter, and achieve the same result using `heading_level` and/or `heading_size` instead. The reasons behind this are described in more detail in this [issue](https://github.com/alphagov/govuk_publishing_components/issues/1953).
This swaps `is_page_heading` for `heading_level` 1.
⚠️  This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) …
=> Use `heading_level` param instead of `is_page_heading` (radio component)

app/views/subscriptions_management/index.html.erb
This relative link is presented on a page that resides on `/email/manage` and returns a 404 (resolving in `/email/help/get-emails-about-updates-to-govuk` so we make it absolute to fix the issue.
Flagged by users while on 2nd line
=> Fix 'find out how to subscribe' link

Gemfile, Gemfile.lock, app/controllers/subscriber_authentication_controller.rb, config/routes.rb, spec/controllers/subscriber_authentication_controller_spec.rb, spec/spec_helper.rb
We added a new endpoint to email-alert-api to authenticate a user by
GOV.UK Account, returning the subscriber details if the email address
is verified and matches a subscriber.  This commit makes the
corresponding change on the email-alert-frontend side, exposing that
feature to users.
This is not complete, we still need to solve some design issues, like:
- What do we show in the error cases?
- Do we prompt a user to explicitly "link" the accounts, rather than
just sign them in?
- Do we forbid users from changing their notifications email address
if it's linked to an account?  Would it be confusing if the addresses
get out of sync?
So for now it's hidden behind a feature flag.
See also https://github.com/alphagov/email-alert-api/pull/1638
---
[Trello …
=> Add a controller method to authenticate a user by GOV.UK Account

app/controllers/subscriber_authentication_controller.rb, spec/controllers/subscriber_authentication_controller_spec.rb
email-alert-api returns a 422 if no session is provided so, rather
than call email-alert-api, redirect the user to authenticate.
---
[Trello card](https://trello.com/c/H0gos8kf/873-backend-work-to-allow-logging-in-to-email-alert-frontend-with-an-account)
[Sentry error](https://sentry.io/organizations/govuk/issues/2474543806/?project=202220&query=is%3Aunresolved)
=> Re-authenticate the user if they don't have a session header

app/controllers/subscriber_authentication_controller.rb, spec/controllers/subscriber_authentication_controller_spec.rb
We're now having email-alert-api create a new Subscriber if a user
logs in via their GOV.UK Account and they haven't used Notifications
before.
See also https://github.com/alphagov/email-alert-api/pull/1643
---
[Trello card](https://trello.com/c/Vzd8so2T/874-implement-designs-for-managing-your-email-notifications-via-the-account)
=> Remove case where a user has a GOV.UK Account but no Subscriber

app/controllers/subscriber_authentication_controller.rb, app/controllers/subscriptions_management_controller.rb, app/helpers/sessions_helper.rb, app/views/subscriber_authentication/confirm_your_govuk_account.html.erb, app/views/subscriber_authentication/sign_in.html.erb, app/views/subscriber_authentication/use_your_govuk_account.html.erb, app/views/subscriptions_management/index.html.erb, config/locales/subscriber_authentication.yml, spec/controllers/subscriber_authentication_controller_spec.rb, spec/controllers/subscriptions_management_controller_spec.rb, spec/support/session_helper.rb
Various frontend changes for account-based email management.  None of these words or screens have been reviewed by a designer, this is just so we can get something working up on staging (it's behind the feature flag) and then iterate.
---
[Trello card](https://trello.com/c/Vzd8so2T/874-implement-designs-for-managing-your-email-notifications-via-the-account)
=> Various frontend changes for accounts

app/assets/stylesheets/application.scss, app/assets/stylesheets/mixins/_govuk-template-link-focus-override.scss, app/controllers/application_controller.rb, app/views/layouts/application.html.erb
Update link styles and swap to `gem_layout`
For consistency across frontend applications.
=> Update link styles and swap to `gem_layout`

app/assets/stylesheets/application.scss, app/controllers/application_controller.rb, app/controllers/subscriptions_management_controller.rb, app/views/content_item_signups/confirm.html.erb, app/views/content_item_signups/taxon.html.erb, app/views/email_alert_signups/new.html.erb, app/views/layouts/application.html.erb, app/views/subscriber_authentication/check_email.html.erb, app/views/subscriber_authentication/confirm_your_govuk_account.html.erb, app/views/subscriber_authentication/sign_in.html.erb, app/views/subscriber_authentication/use_your_govuk_account.html.erb, app/views/subscription_authentication/expired.html.erb, app/views/subscriptions/check_email.html.erb, app/views/subscriptions/new_address.html.erb, app/views/subscriptions/new_frequency.html.erb, app/views/subscriptions_management/confirm_unsubscribe_all.html.erb, app/views/subscriptions_management/index.html.erb, app/views/subscriptions_management/update_address.html.erb, app/views/subscriptions_management/update_frequency.html.erb, app/views/unsubscriptions/confirm.html.erb, app/views/unsubscriptions/confirm_already_unsubscribed.html.erb, app/views/unsubscriptions/confirmed.html.erb
The accounts team are working towards the goal of enabling users who have linked their email notifications address and their GOVUK Account to manage their email subscriptions through their account.
Part of this work is making the email management pages (which live in `email-alert-frontend`) look the same as the account manager when the user is authenticated with a linked account.
This PR reorganises some of the views and requests the `gem_layout_account_manager` from static which will automatically apply account page furniture to the email management pages when the user is logged in with a linked account.
(if you're going to review this I would highly recommend the "Hide whitespace changes option)
Dependent on: 
- https://github.com/alphagov/govuk_publishing_components/pull/2255
- …
=> Account layout for email management pages

app/assets/javascripts/modules/track-email-alert-signup-choices.js, package.json, spec/javascripts/modules/track-email-alert-signup-choices.spec.js
Trello: https://trello.com/c/NtyIMawD/563-remove-jquery-from-email-alert-frontend
This app had a very low dependency on jQuery already, so it only needed
the initialisation function changing on the sole module.
=> Remove jQuery from the app

app/views/subscriber_authentication/sign_in.html.erb, config/locales/subscriber_authentication.yml
We frequently get support tickets along the lines of "I've entered my
email address on this page a dozen times and got not emails!  Your
system is preventing me from signing up to notifications on XYZ!"
But the problem is that you can't sign up to new notifications from
this page.  The text on this page doesn't say that, and the text on
the next page says to contact support.  So, users who find this page
first get frustrated.
So, really emphasise that this is for *existing* subscriptions, not
new ones.
---
=> Clarify that you can only manage existing subscriptions here

app/controllers/link_accounts_controller.rb, app/controllers/subscriber_authentication_controller.rb, app/helpers/account_helper.rb, app/views/link_accounts/show.html.erb, config/locales/link_accounts.yml, config/routes.rb, spec/controllers/link_accounts_controller_spec.rb
[Trello](https://trello.com/c/WSFGT2rz/941-implement-basic-things-are-changing-screen-with-placeholder-content)
**Draft pending final content**
Add a new page, hidden behnd the account feature flag.
Creates a  page with:
- A header
- Some descriptive paragraphs
- A call to action button
The button varies it's content based on if the user is logged in or not.
In either case the user is directed to the same path, as it will start an authenticated request that will send the user down the sign in journey if they are not logged in.
=> Things are changing

.gitignore
`git status` is unhappy about it and we already do this on [other repos](https://github.com/alphagov/account-api/blob/main/.gitignore#L8)
=> Add bundle folder to .gitignore

app/controllers/subscriptions_management_controller.rb, spec/controllers/subscriptions_management_controller_spec.rb
When a user is logged in to a GOV.UK account, we send them to the account
manager to manage their email address. Switch to getting this URL from
`govuk_personalisation` instead so it's consistent with other apps.
https://trello.com/c/u35RYZZW/1030-use-govukpersonalisation-for-change-email-link-in-email-alert-frontend
=> Use `govuk_personalisation` for change email link

app/views/subscriptions_management/index.html.erb, spec/features/unsubscribe_spec.rb, spec/views/subscriptions_management/index.html.erb_spec.rb
The "manage your email subscriptions" page lists all the email notifications a user is currently subscribed to. 
Each of the items on the list has a "Change how often you get emails" link and "Unsubscribe" link. 
The links do not specify which topic they are connected to, therefore to a user navigating the page using a screen reader, it would not be so clear what the purpose of the links is.
This adds some hidden text to the links which references which page/topic they are related to. This way, the page will remain unchanged for sighted users, while improving the experience for screen reader users.
https://trello.com/c/VpmI0ix1
⚠️  This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-p …
=> Fix accessibility issue (link purpose in context) – subscriptions management page

app/controllers/account_subscriptions_controller.rb, app/views/account_subscriptions/confirm.html.erb, config/locales/account_subscriptions.yml, config/routes.rb, spec/controllers/account_subscriptions_controller_spec.rb
This page handles signing up to notifications connected to the
account, which means it also handles the "linking" of an account-api
`OidcUser` to an email-alert-api `Subscriber`.
If a user has subscriptions which pre-date their account, we'll list
them so that the user knows what is changing.  The linking process
also triggers an email in this case (email-alert-api does this).
This page is intentionally very generic: it's not just for single-page
notifications, or content item subscriptions, it's for topics in
general.  This is so we can use this page across different sorts of
email journeys.
---
The frontend for this isn't quite right, the spacing around the button looks weird and the previous subscriptions don't look like a list:
---
[Trello …
=> Add a confirmation page for creating an account subscription

app/views/subscriber_authentication/no_subscriber.html.erb, config/locales/subscriber_authentication.yml
This page doesn't match the designs: the email address is not
bold (and the link following it is), and the first sentence under the
"How to get emails about updates to GOV.UK" heading is missing.
I've also changed the `<div>`s to `<p>`s.
---
[Trello card](https://trello.com/c/5ZoujfPL/1115-implement-email-management-account-sniffer-logic)
=> Fix "not subscribed" content

app/controllers/subscriber_authentication_controller.rb, app/services/verify_subscriber_email_service.rb, app/views/subscriber_authentication/sign_in.html.erb, app/views/subscriber_authentication/use_your_govuk_account.html.erb, config/locales/subscriber_authentication.yml, spec/controllers/subscriber_authentication_controller_spec.rb, spec/services/verify_subscriber_email_service_spec.rb
When a user comes to `/email/manage/authenticate`, they enter an email
address in a form.  We want to then:
- just log them in to email-alert-frontend, if they're logged into a
GOV.UK account and that GOV.UK account has the same email address; or
- tell them to sign in with their account, if there is a GOV.UK
account with the same email address but they're not logged into it; or
- fall back to the current magic link journey if the email address
does not belong to a GOV.UK account.
---
[Trello card](https://trello.com/c/5ZoujfPL/1115-implement-email-management-account-sniffer-logic)
=> Implement subscriber account authentication

app/controllers/account_subscriptions_controller.rb, app/controllers/subscriptions_controller.rb, app/services/create_account_subscription_service.rb, app/services/verify_subscription_email_service.rb, app/views/subscriptions/use_your_govuk_account.html.erb, config/locales/subscriptions.yml, config/routes.rb, spec/controllers/account_subscriptions_controller_spec.rb, spec/controllers/subscriptions_controller_spec.rb
We want to make two changes to the new topic subscription journey.  The current journey is like so:
1. User ends up on `/email/subscriptions/new?topic_id=...`, which shows a form which asks what frequency they want
2. User submits the frequency
3. User is asked for their email address
4. User submits the email address
5. User is sent an email with a link to click to approve the new subscription
**The first change happens between steps 2 and 3:**
If the user is logged in at this point, we don't ask for their email address.  We just link their notifications to their GOV.UK account (which will send an email if they had prior unlinked active subscriptions), create the subscription, and send them to the subscriptions management page.  This bypasses step 3 onwards.
If the session is invalid …
=> Implement account-based topic subscriptions

app/controllers/single_page_subscriptions_controller.rb, app/views/development/index.html.erb, app/views/single_page_subscriptions/show.html.erb, config/locales/single_page_subscriptions.yml, config/routes.rb, spec/controllers/single_page_subscriptions_controller_spec.rb
[Trello](https://trello.com/c/DsqzirDG/1065-implement-single-page-notifications-button-handling-page)
[Figma](https://www.figma.com/file/9RzsNFl3iYBXM5QfKO2HkE/Single-page-notifications-feature?node-id=1433%3A21852)
Adds logic and tests for logic that signs users up to single page notifications.
Including a informational screen for logged out users.
We'll need to ensure users have a valid logged in session, with linked accounts before creating a subscription.
We can do those checks automatically for logged in users.
For logged out users we'll need to give them some information, and present a button that posts to DI's Single Sign on/up form, with the right params to return them and sign them up afterwards.
=> Single page handler

app/views/single_page_subscriptions/show.html.erb, config/locales/single_page_subscriptions.yml
The interrupt page is intended to give users more information before
signing up or registering to a linked GOV.UK Account and notification.
We've recently launched the /sign-in page that is intended to help users
navigate through account confusion. We can link to that page here, so
users can explore onwards if they are confused at this point, and return
to this journey later.
=> Add /sign-in link to inset on interrupt page

app/services/create_account_subscription_service.rb, spec/controllers/account_subscriptions_controller_spec.rb, spec/controllers/single_page_subscriptions_controller_spec.rb, spec/controllers/subscriptions_controller_spec.rb
If someone is signed into a GOV.UK account, they must have already
confirmed their email address when they created the account. They also
will have clicked a button or gone through a form to sign up to the email
notifications.
This means we don't need to send them an additional confirmation email
like we do for people who aren't using a GOV.UK account.
=> Don't send confirmation emails for GOV.UK account users

app/controllers/single_page_subscriptions_controller.rb, app/views/single_page_subscriptions/show.html.erb, spec/controllers/single_page_subscriptions_controller_spec.rb
This is to be consistent with what we're calling the parameter in the
component and in account-api.
---
[Trello card](https://trello.com/c/oOpGMmxF/1126-put-the-single-page-signup-button-on-some-pages)
=> Rename single-page subscriptions parameter to base_path

app/views/subscriptions/use_your_govuk_account.html.erb
This should go to the `verify_subscription_account` route (which is
otherwise unreachable), as that's what redirects to the confirmation
page with the appropriate parameters.
=> Fix target and fields for account topic subscriptions

app/services/create_account_subscription_service.rb, spec/controllers/account_subscriptions_controller_spec.rb, spec/controllers/single_page_subscriptions_controller_spec.rb, spec/controllers/subscriptions_controller_spec.rb
We don't send these for brexit checker subscriptions created through
account-api, but for normal subscriptions created through this app, we
do want them.
=> Send confirmation email when creating an account subscription

app/controllers/single_page_subscriptions_controller.rb, app/views/single_page_subscriptions/show.html.erb, spec/controllers/single_page_subscriptions_controller_spec.rb
The confirmation page expects a `topic_id` parameter, which is the
slug of the `SubscriberList`.
This commit has a slight change of behaviour: previously we wouldn't
call email-alert-api to find-or-create the `SubscriberList` if the
user were logged out.  Now we do, so that we can get the slug.
I also changed some `[]`s into `fetch`es where the values are
required, and removed a redundant `rescue` (which is handled by a
`rescue_from` in the `ApplicationController`).
---
[Trello card](https://trello.com/c/05BtVxFZ/1100-prep-to-qa-single-page-notifications-journeys)
=> Pass topic_id of single-page subscription to account confirm page

app/controllers/account_subscriptions_controller.rb, app/views/account_subscriptions/confirm.html.erb
We use this in a couple of places, but it's not actually set by the
`before_action`.
---
[Trello card](https://trello.com/c/GKKcketU/1132-qa-snag-list)
=> Fix references to `return_to_url` instance var

app/controllers/single_page_subscriptions_controller.rb
The parameter is called "title", not "name".  Previously this was
obscured by this call not being made if the user is logged out.
---
[Trello card](https://trello.com/c/GKKcketU/1132-qa-snag-list)
=> Fix invocation of find_or_create_subscriber_list

app/controllers/account_subscriptions_controller.rb, spec/controllers/account_subscriptions_controller_spec.rb
`authenticate_subscriber_by_govuk_account` throws a 422 error if the
`govuk_account_session` parameter is not given, because it's
mandatory.
But the `rescue_from`s in this controller didn't handle that, and so
if an unauthenticated user got to this page somehow, they would be
served a 400 error.  This situation is unlikely (I only triggered it
by logging out and then manually visiting the URL) but still not
great.
So, gracefully handle this case, by checking if a session exists at
all before trying to use it.
---
[Trello card](https://trello.com/c/GKKcketU/1132-qa-snag-list)
=> Reauthenticate user if they have no session

app/controllers/application_controller.rb, app/controllers/subscriber_authentication_controller.rb, app/controllers/subscriptions_management_controller.rb, app/helpers/sessions_helper.rb, spec/controllers/subscriber_authentication_controller_spec.rb, spec/controllers/subscriptions_management_controller_spec.rb, spec/support/session_helper.rb
If a user is signing in to this app via their GOV.UK account, we don't
want to create a separate session cookie: if we do, we then have to
tie together deleting the email-alert-frontend session cookie when we
log a user out, and it's potentially confusing that the
email-alert-frontend session cookie will expire before the
`__Host-govuk_account_session` one
So, we change the authentication in this app to *preferentially* use
the GOV.UK account (see `authenticated_via_account?` ahead of
`session["authentication"}.present?` in the conditional).
When using account auth, no session cookie is created, we fall back to
linking with an email-alert-api subscriber on every request.  This
will be slower, but we can keep an eye on performance, as we expect a
gradual ramp-up of notifications users also …
=> Do not create a session cookie for account users

app/assets/stylesheets/application.scss, app/controllers/subscriptions_management_controller.rb, app/views/layouts/application.html.erb, app/views/subscriptions_management/index.html.erb, config/locales/subscriptions_management.yml, spec/controllers/subscriptions_management_controller_spec.rb, spec/features/change_email_frequency_spec.rb, spec/views/subscriptions_management/index.html.erb_spec.rb
See commits for details.
But this isn't quite right currently:
1. The dividers between subscriptions aren't showing up.  There are `<hr>`s in the source (and were before I changed anything), so I guess some CSS is missing somewhere.
2. I don't know how to style the "topic" and "page" headers in the last commit to look like our designs, so I've just added them here to be styled.
---
[Trello card](https://trello.com/c/4MKj7G4o/1135-govuk-account-email-subscriptions-page-design-amends)
=> Accounts frontend changes from QA session

app/controllers/single_page_subscriptions_controller.rb, spec/controllers/single_page_subscriptions_controller_spec.rb
This is so it matches the information we give to users as they go through the subscription journey.
[Trello](https://trello.com/c/Goq1BJZP/1155-change-default-frequency-of-single-page-notifications-to-as-updates-happen)
=> Change default single page notification frequency to immediately

app/views/single_page_subscriptions/show.html.erb
The comma was missing which meant the extra parameters were passed to
`single_page_new_session_path` and ended up as parameters in the action
URL, rather than attributes in the rendered HTML.
[Trello](https://trello.com/c/3NvEng3t/1159-fix-passing-ga-cookie-consent-parameters-from-email-subscriptions-the-way-you-subscribe-page-to-di)
=> Fix arguments to sign in form

app/views/subscriptions_management/index.html.erb
We increased the size of this heading to `xl`, but that is too large.
Change the heading back to `l` size.
https://trello.com/c/pPJCeMT9/1157-make-email-subscriptions-management-page-heading-smaller
=> Make h1 on the email subscriptions management page smaller

app/helpers/subscriptions_helper.rb, app/views/subscriptions_management/index.html.erb, config/locales/subscriptions_management.yml, spec/controllers/subscriptions_management_controller_spec.rb, spec/helpers/subscriptions_helper_spec.rb
Since these subscriptions are for a single page, we can show the user
the last time they were updated so they can see if and when they would
have received an email about it.
This does call the content store once per single page subscription the
user has which could cause performance problems if a user has many
subscriptions. It should be fine for now but it's something we should
keep an eye on.
[Trello](https://trello.com/c/Z9b4Ar5z/1156-update-email-subscriptions-management-page-content)
[Figma](https://www.figma.com/file/9RzsNFl3iYBXM5QfKO2HkE/Single-page-notifications-feature?node-id=4%3A2237)
Screenshot with the new text: 
⚠️  This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pu …
=> Show last update date for single page subscriptions

app/controllers/single_page_subscriptions_controller.rb, config/routes.rb, spec/controllers/single_page_subscriptions_controller_spec.rb
[Trello](https://trello.com/c/GptIhNbO/1160-refactor-single-page-notifications-controller-to-display-sign-in-page-using-two-requests)
We were fighting the RESTful framework when we wrote this.
In a perfect world the user is logged in and the initail POST request, goes and changes the state of their email subscriptions. However if they are not logged in we can't do that and we drop them out into an information screen with a request to log in or sign up.
Initially we had this screen being returned as a result of the POST request.
The more REST-y thing to do is to create a separate :show method on it's own GET route.
So that's what we're doing here.
Along the way I refactor out a bit of the topic_id stuff to safeguard against it not being there when we need it during :edit or :show journeys.
=> RESTore sign up routes

app/views/subscriber_authentication/sign_in.html.erb, config/locales/subscriber_authentication.yml
So it's clearer to users what they can and can't do when managing their
email subscriptions.
[Trello](https://trello.com/c/pHKLRXYy/1161-update-text-on-the-sniffer-page-change-your-email-preferences)
=> Update content on sign in page

app/helpers/subscriptions_helper.rb, app/views/subscriptions_management/index.html.erb, config/locales/subscriptions_management.yml, spec/controllers/subscriptions_management_controller_spec.rb, spec/helpers/subscriptions_helper_spec.rb
Make the heading a link for single page subscriptions and change 'created on' to 'you subscribed on' to match our designs.
[Trello](https://trello.com/c/Z9b4Ar5z/1156-update-email-subscriptions-management-page-content)
[Figma](https://www.figma.com/file/9RzsNFl3iYBXM5QfKO2HkE/Single-page-notifications-feature?node-id=4%3A2237)
There's a third item on the linked Trello card - the change for that will come in a separate PR.
The new page with a single page subscription:
=> Update content on email management pages

app/controllers/single_page_subscriptions_controller.rb, spec/controllers/single_page_subscriptions_controller_spec.rb
In #1193 we changed the default email frequency from 'daily' to
'immediately'. However, we only changed it in the branch of the
`SinglePageSubscriptions#create` method for signed in users.
This meant that users who need to sign in and then return to
`AccountSubscriptionsController#confirm` were still getting the 'daily'
frequency.
Set the frequency parameter in the callback URL so it's passed through
to the other controller. Also take the opportunity to define it as a
variable in the controller to avoid repetition.
=> Fix default email frequency for signed out users

app/controllers/subscriptions_management_controller.rb, app/helpers/frequencies_helper.rb, app/views/subscriptions_management/update_frequency.html.erb, config/locales/frequencies.yml, spec/controllers/subscriptions_management_controller_spec.rb
The text for the `immediate` frequency didn't make sense for single page
subscriptions because there will never be a case where a page is added
to a single page subscription.
[Trello](https://trello.com/c/ZZ3TEybY/1163-update-content-for-frequency-of-single-page-subscription-emails)
The new content for single page subscriptions:
=> Update radio options for single page subscriptions

app/controllers/account_subscriptions_controller.rb, app/controllers/subscription_authentication_controller.rb, app/controllers/subscriptions_controller.rb, app/services/create_account_subscription_service.rb, app/views/subscriptions_management/index.html.erb, config/locales/subscription_authentication.yml, config/locales/subscriptions_management.yml, spec/controllers/account_subscriptions_controller_spec.rb, spec/controllers/subscription_authentication_controller_spec.rb, spec/controllers/subscriptions_controller_spec.rb, spec/features/subscribe_verify_email_spec.rb, spec/views/subscriptions_management/index.html.erb_spec.rb
We introduced a regression, where creating a topic subscription
through the account would not show a success flash message on the
manage page.  This commit fixes that, and also updates the content of
the flash to match our designs.
I could have made the template use the account flash, but decided
that, as we have both account and non-account topic subscriptions for
now, it would be best for them to both use the same approach.  So
these flash messages do not use the account flash.
I also changed some places where we were redirecting to the manage
page via the `process_govuk_account_path`, even though we know at this
point the user is signed in.
---
---
[Trello card](https://trello.com/c/CufkfjRa/1164-fix-flash-messages-when-subscribing-to-a-topic)
=> Bring black flash message for topic subscriptions

app/views/subscriptions_management/index.html.erb, spec/controllers/subscriptions_management_controller_spec.rb
The checker doesn't exist anymore so this will just redirect to gov.uk/brexit
=> Remove link to view Brexit checker results

app/views/single_page_subscriptions/show.html.erb
In addition to cross-domain tracking, the "Create a GOV.UK account or
sign in" button on the [The way you subscribe to emails from GOV.UK is
changing](https://www.gov.uk/email/subscriptions/single-page/new?topic_id=open-standards-for-government) page also needs explicit click tracking as per our PA's
advice.
=> Add click tracking to button

app/controllers/account_subscriptions_controller.rb, app/controllers/application_controller.rb, app/controllers/single_page_subscriptions_controller.rb, app/controllers/subscriber_authentication_controller.rb, app/controllers/subscriptions_controller.rb, app/helpers/account_helper.rb, app/services/create_account_subscription_service.rb, app/services/verify_subscriber_email_service.rb, app/services/verify_subscription_email_service.rb, spec/controllers/account_subscriptions_controller_spec.rb, spec/controllers/single_page_subscriptions_controller_spec.rb, spec/controllers/subscriber_authentication_controller_spec.rb, spec/controllers/subscriptions_controller_spec.rb, spec/services/verify_subscriber_email_service_spec.rb, spec/services/verify_subscription_email_service_spec.rb
We've switched this on in production and are confident we won't be
switching it off.
The diff to the tests will be much easier to review if you hide whitespace changes.
=> Remove `govuk_account_auth_enabled?` feature flag

app/views/subscriptions_management/index.html.erb
Add data attributes for tracking to the "Unsubscribe" and "Change how often you get emails" links on "Manage your GOV.UK email subscriptions".
https://trello.com/c/3tRhGf2w
=> Add tracking to Manage your emails page links

app/controllers/account_subscriptions_controller.rb, app/services/create_account_subscription_service.rb, spec/controllers/account_subscriptions_controller_spec.rb
Previously, if a user was signed out and clicked the 'get emails about
this page' button to subscribe to email alerts about a single page, we
didn't check if they already had a subscription to that page.
If they did we'd ask them to confirm again and send a new confirmation
email, but the manage emails page would show the date of when they
originally subscribed which was a bit confusing.
Now, do that check and if they're already subscribed redirect them back
to the content page after they sign in with a flash message to display
an info banner telling them they were already subscribed.
Note that this implementation does skip the confirmation page after signing 
in. We think this is ok - we're checking that the user is successfully logged 
in before we do anything (so we can't leak …
=> Handle signed out users who are already subscribed to a page

app/views/subscriptions_management/index.html.erb, config/locales/subscriptions_management.yml, spec/controllers/subscriptions_management_controller_spec.rb
Having two lines was potentially confusing, so simplify them into a
single line.
[Trello](https://trello.com/c/1P4BQE4t/1220-changing-frequency-content-change-index-page)
Screenshot of the new text on the manage page:
=> Simplify frequency information content

app/views/single_page_subscriptions/show.html.erb, config/locales/single_page_subscriptions.yml
[Trello](https://trello.com/c/a1mZyxzA/1221-interrupt-page-text-for-people-who-already-have-email-subscriptions)
Here's the thinking:
Page h1 change: Consistency and clarity. We talk about email
subscriptions and about getting emails, not about subscribing to emails.
Adding the  H2 ‘If you have other GOV.UK email subscriptions’ to
reassure users who are worried about their other subscriptions.
Adding the H2 ‘Create a GOV.UK account or sign in’ for accessibility -
the green button needs to be nested under a heading that describes it
coherently.
=> Content update to New single page subs page

app/helpers/subscriptions_management_helper.rb, app/views/subscriptions_management/update_frequency.html.erb, config/locales/subscriptions_management.yml, spec/controllers/subscriptions_management_controller_spec.rb, spec/helpers/subscriptions_management_helper_spec.rb
Previously there was no mention of what subscription you're changing the
frequency of on this page which was confusing. Add the title from the
subscriber list so people know what they're changing.
Having `@subscriptions[@subscription_id]["subscriber_list"]["title"]` in
the view is a bit ugly, so add a new `SubscriptionsManagementHelper`
module to hold some new methods that are only used in the view.
[Trello](https://trello.com/c/ojh8IxlC/1223-changing-frequency-content-manage-page)
Screenshot of the new heading: 
=> Show subscription name on the update frequency page

app/controllers/single_page_subscriptions_controller.rb, spec/controllers/single_page_subscriptions_controller_spec.rb
So that we can store it on email alert API and use it in emails. This is
currently only for single page subscriber lists, see [[1]] for more
details on the API side.
[Trello](https://trello.com/c/dm5ZxFVB/1226-pass-through-page-descriptions-to-subscriberlists-on-major-minor-publishing-change)
[1]: https://github.com/alphagov/email-alert-api/pull/1705
=> Pass page description when creating a subscriber list

app/controllers/account_subscriptions_controller.rb, spec/controllers/account_subscriptions_controller_spec.rb
When a user tries to subscribe to a list with their account, we
redirect back to its URL if they're already subscribed.  But this
means that we throw an error for lists without a URL[1].
This can happen if a user, who has already linked their notifications
to their account, goes to sign up to a list-without-a-url which they
have already signed up to, as we redirect such users to continue via
their account (see `verify_account` in `subscriptions_controller.rb`)
[1] https://sentry.io/organizations/govuk/issues/2950527269/
=> Handle repeat-subscribing to a list without a URL via the account

app/controllers/subscriber_authentication_controller.rb, spec/controllers/subscriber_authentication_controller_spec.rb
When an unauthenticated user tries to go to `/email/manage` they are
redirected through the sign in process. If they sign in with a GOV.UK
account this means they'll be taken off the `www.gov.uk` domain which
breaks the analytics tracking when they return as we weren't preserving
the linker parameters GOV.UK sign in are passing back to the app.
Now, pass through the parameters in the final redirect so they're
present on the page that Google Analytics loads on. Also add a test so
we don't accidentally break this in the future.
[Trello](https://trello.com/c/nNT2WjDH/1088-account-manager-tracking-and-reporting-update-after-di-migration)
⚠️  This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your …
=> Pass analytics params when signing in to manage page

app/views/subscriber_authentication/sign_in.html.erb
Submitting this form never takes you directly to the OAuth provider.
A user either:
1. Has a GOV.UK account and is signed in. They are redirected
through to the subscriptions page without needing to sign in.
2. Has a GOV.UK account and is not signed in. They are shown a
page that tells them they have a GOV.UK account and must sign
in again. There's a button on the page which redirects them to
the OAuth provider which has the cross domain tracking
parameters on the link.
3. They have an account using the old system of sending a
magic link to their email address. Here, they see a page
telling them to check their email for an sign in link, which
will take them to the subscriptions page.
The case that sends the user to sign in again is 2, but this form isn't
the last one in this app before …
=> Remove cross domain tracking parameters from sign in page

app/controllers/subscriptions_management_controller.rb, app/views/subscriptions_management/index.html.erb, config/locales/subscriptions_management.yml
Implement layout updates for the Manage your emails page:
- use the account layout without a left hand side nav
- update the inset text with a link to manage your GOVUK details
(appears only when the user is authenticated with a GOVUK account)
- add an unsubscribe from everything button lower down the page (this
was in the inset text but was replaced by the aforementioned info on
how to update one's email address)
https://trello.com/c/bPoMTXr0
https://user-images.githubusercontent.com/7116819/157088778-67d45995-a6e2-454b-8a79-5ce71d8ed356.mov
https://user-images.githubusercontent.com/7116819/157089590-9e38f1e1-4f16-4222-ba9e-e012b4ca0c7c.mov
⚠️  This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#me …
=> Manage your GOVUK emails layout update

app/views/account_subscriptions/confirm.html.erb, config/locales/account_subscriptions.yml
In [[1]] we removed the first time sign up page that asked users for
consent to use cookies, to email them for feedback, and displayed
privacy information about how we use the data associated with their
account.
We're not going to be collecting consent for cookies or feedback
centrally in the account any more, so that doesn't need moving, but we
do need to show users the privacy information at some point in the
creation journey.
Add this information to the confirmation page instead, so users can
read it before finalising their subscriptions.
[1]: https://github.com/alphagov/frontend/pull/3224
---
*DO NOT MERGE* until [the PR to remove the first time sign in page](https://github.com/alphagov/frontend/pull/3224) is ready. These need to be deployed at the same time
--- …
=> Add account privacy information to subscription confirmation page

app/models/auth_token.rb, config/application.rb, spec/models/auth_token_spec.rb, spec/support/token_helper.rb
- Makes SHA256 tokens the default again (as per Rails 7 defaults)
- Adds a rotate to the decrypter that allows it to accept SHA1 tokens as well as SHA256 tokens.
This will allow it to accept the current SHA1 tokens from email-alert-api, and the SHA256 tokens from when email-alert-api is updated properly.
https://trello.com/c/Iz4TyAzx/1321-fixes-for-email-alert-api-email-alert-frontend-update-incident
Note - due to the way email-alert-api is set up, not currently possible to test this end to end. Has been tested by generating a token in the email-alert-api integration console:
`token = …
=> Allow AuthToken to accept SHA256 or SHA1 hashes

config/locales/subscriptions_management.yml
Amend content of the account callout on the "Manage your GOVUK email subscriptions" page.
https://govukverify.atlassian.net/browse/GUA-224
=> Update content on manage your subscriptions page

app/views/subscriptions_management/index.html.erb, spec/controllers/subscriptions_management_controller_spec.rb
Adjustment to the "Subscriptions for emailaddress" snippet so that is no
longer a heading but a regular paragraph with the email address in bold.
=> Minor markup adjustment on Manage your emails page

config/application.rb
SHA1 -> SHA256 cookie rotation no longer necessary.
=> Remove cookie rotation code.

app/controllers/subscriptions_management_controller.rb
~🙅🏻‍♀️**Do not merge**🙅🏻‍♀️, depends on https://github.com/alphagov/static/pull/2808~ 
Replacing `gem_layout_account_manager_no_nav` with
`gem_layout_account_manager` since the "no nav" bit has become irrelevant
since this page is the last page on GOVUK using the account layout
template.
There should be no visual change. 
The next step will be to remove `gem_layout_account_manager_no_nav` from `static` entirely as this is the last place referencing it.
=> Account layout template rename

app.json
This sets the GOVUK_PROXY_STATIC_ENABLED env var to enable the proxy to Static in production. This is so the application continues, when Static changes to use relative URLs for assets. See https://github.com/alphagov/govuk_app_config/pull/261 and https://github.com/alphagov/govuk-puppet/pull/11801
=> Enable Static proxy for Heroku deployments

app/controllers/single_page_subscriptions_controller.rb, app/controllers/subscriptions_controller.rb, spec/controllers/single_page_subscriptions_controller_spec.rb, spec/controllers/subscriptions_controller_spec.rb
Since we're not doing anything about these (they're just background noise of hacking attempts), we catch these errors and return 422s instead of crashing. To make sure we can still monitor if we want to, add the error details as logged warnings.
This also pulls the URL parsing that's done in the content store API call forwards into email-alert-frontend so we protect content store from bogus calls.
https://trello.com/c/Wd2RY7tJ/1632-silence-bad-uri-errors-on-email-alert-frontend
=> Prevent Bad URI errors from getting into Sentry

config/environments/production.rb
This change ensures that CSS and JS is optimized on production. The settings used are consistent with other frontend rendering applications.
We are currently serving larger asset sizes than required to end users, optimizing the CSS and JS should improve performance on the frontend.
The table below shows the results when CSS and JS is optimized:
| asset | current size (resource / network) | optimized size (resource / network) |
| --- | --- | --- |
| app.css | 28.8 kB / 3.3 kB | 23.6 kB / 3.1 kB |
| app.js | 177 kB / 26.7 kB | 65.6 kB / 11.4 kB |
Total size saved when transferring the CSS and JS over the network is around 15.5 kB.
Trello card: https://trello.com/c/uxPZxhqq/1706-email-alert-frontend-css-and-js-not-optimized
---
⚠️  This repo is Continuously Deployed: make sure you [follow …
=> Optimize CSS and JS on production

.dockerignore
Since we always build from a clean working copy, there's no benefit to having `vendor` in dockerignore. It just creates a slight risk of confusion in future if someone were to check in third-party JS/CSS files into `vendor/{javascripts,stylesheets}` that were needed at runtime, as has been done for some GOV.UK apps.
No change for EC2/Puppet (i.e. the current production system).
=> Sort .dockerignore and remove `vendor` from it.

app/views/single_page_subscriptions/show.html.erb
Hi @andysellick - Would you be able to review this? Thanks :+1:
Adds the `ga4-link-tracker` to the `Create a GOV.UK account or sign in` button on [these types of page](https://www.gov.uk/email/subscriptions/single-page/new?topic_id=cost-of-living-payment)
We were asked to add this button as a link to be tracked. [See trello card](https://trello.com/c/uRQJP1gE/401-subscription-page-not-tracking-external-links).
To test this branch, use `govuk-docker`. Note that you run `make email-alert-frontend` as usual, but to start the server you need to use `govuk-docker up email-alert-frontend-live` otherwise the static assets do not load.
Here's a page you can test : http://email-alert-frontend.dev.gov.uk/email/subscriptions/single-page/new?topic_id=cost-of-living-payment
⚠️  This repo is …
=> Add GA4 link tracking to 'Create a GOV.UK account or sign in' button

config/locales/single_page_subscriptions.yml, config/locales/subscriber_authentication.yml, config/locales/subscriptions.yml, config/locales/subscriptions_management.yml
The GOV.UK account is being rebranded to GOV.UK One Login. These are all content updates necessary to support this change
https://trello.com/c/EbkPjP8y/1817-thursday-9th-feb-email-alerts-pr-approvals-for-digital-identity-accounts-team
=> GUA-523: GOVUK account name change

app/assets/config/manifest.js, app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb, config/application.rb
https://trello.com/c/ws6n64fm/1870-enable-individual-loading-of-stylesheets-in-email-alert-frontend
Changes to load component and view style sheets only required on the page being viewed. For example, CSS for "radio" only loads on the following pages:
- https://www.integration.publishing.service.gov.uk/email-signup/?link=/money
This reduces the amount of CSS required for each page and increases the ability of a browser to cache the stylesheets - this should mean a faster load time for both first time and repeat visitors.
See [RFC #149](https://github.com/alphagov/govuk-rfcs/pull/152) for more details.
- https://www.integration.publishing.service.gov.uk/email-signup/?link=/money
- https://www.integration.publishing.service.gov.uk/foreign-travel-advice/canada/email-signup
- …
=> Configure AssetHelper to load individual stylesheets

app/controllers/content_item_signups_controller.rb
This code was originally introduced to handle special cases for subscriptions. However, this affected sign-ups for other pages using this same flow, since the value of the `single_page_subscription` can be present but a string with the value of false. This meant that for non single page subscriptions, the subscriptions were still going through the single page flow, resulting in users not receiving email alerts for content changes.
=> Hotfix for single page subscriptions

app/controllers/subscriptions_management_controller.rb, spec/controllers/subscriptions_management_controller_spec.rb
In order to improve the logged-in experience, in https://github.com/alphagov/frontend/pull/3670 we are redirecting /account directly to home.account.gov.uk. This means that we are skipping session creation. It improves the general logged in behaviour, but means that if someone goes to /account and logs in, then follows the link to /email/manage, email-alert-frontend will not know that the user is logged in (because no session will exist), and they'll be prompted for their email address. To get around this, we add support for a hint parameter (from=your-services) which will be added to the link in the home.account.gov.uk/your-services page. When we go to /email/manage?from=your-services, the app knows that we came from One Login and are therefore probably logged in, so attempts a silent …
=> Adds handler for from=your-services param hint in /email/manage

app/views/account_subscriptions/confirm.html.erb, app/views/content_item_signups/confirm.html.erb, app/views/content_item_signups/taxon.html.erb, app/views/subscriber_authentication/sign_in.html.erb, app/views/subscriptions/new_address.html.erb, app/views/subscriptions/new_frequency.html.erb, app/views/subscriptions/use_your_govuk_account.html.erb, app/views/subscriptions_management/index.html.erb, app/views/subscriptions_management/update_address.html.erb, app/views/unsubscriptions/confirm.html.erb
Adds GA4 tracking to the various pages involved in the email subscription process.
There's quite a lot of them, and some aren't testable locally as they depend upon a connection to One Login (we might not be able to test them properly until they go live). I've written this PR as separate commits for each page to try to make it as clear as possible, see individual commits for details.
Part of the GA4 migration.
None.
Trello card: https://trello.com/c/TXQOqtZ0/628-email-subscriptions-manage-subscriptions-sign-in-change-unsubscribe-forms
=> Add GA4 tracking to email subscriptions

app/views/subscriptions/use_your_govuk_account.html.erb
Restore some form hidden inputs on the page at https://www.gov.uk/email/subscriptions/verify
These were mistakenly removed in https://github.com/alphagov/email-alert-frontend/pull/1587/commits/40c9de7dee8acf8f636bb63641248da303acd7aa
None.
Trello card: https://trello.com/c/TXQOqtZ0/628-email-subscriptions-manage-subscriptions-sign-in-change-unsubscribe-forms
=> Restoring lost form hidden inputs

spec/features/subscribe_with_account_spec.rb
Adds a regression test for (eg) https://github.com/alphagov/email-alert-frontend/pull/1594. We rely on the hidden fields, and there isn't a great way to check them in controller tests. We add into the feature test a check that when the login button is pressed we so at least get as far as calling the adaptor code that gets the redirect URI.
=> Test redirect in subscribe with account feature

app/controllers/subscriptions_management_controller.rb, app/views/subscriptions_management/confirm_unsubscribe_all.html.erb, app/views/subscriptions_management/index.html.erb, app/views/subscriptions_management/update_frequency.html.erb
Fixes some of the GA4 tracking [previously added](https://github.com/alphagov/email-alert-frontend/pull/1587). See individual commits for details.
None.
Trello card: https://trello.com/c/TXQOqtZ0/628-email-subscriptions-manage-subscriptions-sign-in-change-unsubscribe-forms
=> GA4 tracking fixes

app/controllers/subscriptions_management_controller.rb, app/controllers/unsubscriptions_controller.rb, app/views/subscriptions_management/index.html.erb
- for the index page of the email subscriptions management, when returning from a successful action such as changing the frequency of an email or unsubscribing from all emails
- we need the message (not the description of the message) to be in English for tracking purposes, so we add `message_en` to all of the `flash[:success]` objects, that are used to display the success element as well as track in GA4 that it has appeared
- this was partly done before but not extensively enough (some success tracking was missing text or had the wrong text)
None.
Trello card: …
=> More tracking fixes

app/views/subscriptions_management/confirm_unsubscribe_all.html.erb
Include a value for 'text' in the form tracker GA4 data attributes on the email subscriptions 'unsubscribe from all emails' page.
- text attribute was missing from unsubscribe all form tracker data attributes. This meant that the form tracker was looking and failing to find a value (since the form has no inputs, just the button to confirm)
- hard coding the text attribute into the form data attributes should hopefully fix this
- difficult to test as cannot render page locally
Part of the GA4 migration.
None.
Trello card: https://trello.com/c/Jov85mLj/686-amend-text-value-on-unsubscribe-event-on-unsubscribe-from-a …
=> Fix GA4 text value for unsubscribe all

app/views/govuk_account_signups/show.html.erb, config/locales/single_page_subscriptions.yml
Simplify the interstitial page that comes when a user comes via the single-page-notification-button path and is required to create/use a One Login account.
https://trello.com/c/yxBLErqj/2135-improve-account-journeys-in-email-alert-frontend
BEFORE:
AFTER:
=> Simplify One Login interstitial page

app/views/subscriber_authentication/sign_in.html.erb
- where you enter your email address (https://www.gov.uk/email/manage/authenticate) we have GA4 tracking
- the tracking currently defaults to not collecting any data from the form, so inputs are listed as [redacted]
- we want to make the redaction more specific so it says [email]
- to do this, set an attribute on the form so that values of inputs are collected, but when this occurs we apply our PII stripping code, which means that any email address entered into this field is returned as [email] instead
To make the GA4 data more understandable.
None.
Trello card: …
=> Redact email addresses as [email]

app/services/verify_subscription_email_service.rb
This allows for up to 40 subscriptions per hour. The previous threshold of 11 requests per hour seemed too strict as legitimate users hit this limit. We've confirmed the new limit with FCDO (they brought this to our attention) and they think that the new limit is reasonable.
Trello:
https://trello.com/c/6CwyYXCw/2248-increase-rate-limit-to-40-rpm-for-email-signup-journeys
=> Up hourly rate limit for email subscriptions

config/initializers/dartsass.rb
Suppress Sass dependency deprecation warnings
To only show deprecation warnings originating from the application and GOV.UK Publishing Components while silencing those coming from GOV.UK Frontend.
=> Suppress Sass dependency deprecation warnings

app/views/account_subscriptions/confirm.html.erb
Change the value of `action` for the GA4 event on the 'Confirm you want to get emails' page from `Confirm` to `confirm`.
This was using an existing value from the locale file but this is also used for the visible button text. Given the choice between creating a new entry in the locale file just for this, and simply hard coding it, I went with hard coding on the basis that this isn't text that needs translating - in fact it should always be just `confirm` for the GA4 data.
GA4 event data values like this should normally be lowercase.
None.
Trello card: https://trello.com/c/JDJgPslu/805-lowercase-confirm-action-in- …
=> Change GA4 confirm form action data

app/views/account_subscriptions/confirm.html.erb, app/views/subscriber_authentication/check_email.html.erb, app/views/subscriptions/check_email.html.erb
Adds GA4 tracking to the details component on some pages, specifically the `index_section_count` attribute, which the details component cannot generate itself. In this case all of the details components are by themselves on these pages, so the `index_section_count` is 1.
Details component is on this page: https://www.gov.uk/email/subscriptions/account/confirm?frequency=immediately&return_to_url=true&topic_id=cost-of-living-payments-2023-to-2024
I'm not exactly sure of the URLs of the two other pages where the details component appears, but I've tested the code in an visible page and it functions correctly.
None. …
=> Add tracking to details components

README.md
https://trello.com/c/9rOxWNnD/396-retire-special-route-publisher
=> Update documentation now that special-route-publisher is retired.

app/views/layouts/account.html.erb
Remove the `blue_bar` option from the account layout template
Using the `blue_bar` option in the layout_for_public component has no impact, the blue_bar functionality was removed as part of the brand update
Jira: https://gov-uk.atlassian.net/browse/NAV-18190
=> Remove the `blue_bar` option from the account layout template

app/controllers/application_controller.rb, app/controllers/content_item_signups_controller.rb, app/controllers/email_alert_signups_controller.rb, app/controllers/govuk_account_signups_controller.rb, app/controllers/subscription_authentication_controller.rb, app/controllers/subscriptions_controller.rb, app/controllers/unsubscriptions_controller.rb
- standardise how we mark exceptions to forgery protection - application controller has forgery protection turned on for all routes, so we should mark skips in the specific controllers and use a standardised way of doing that.
- update deprecated `:unprocessable_entity` values to `:unprocessable_content`
Note that this PR triggers the same four code scanning issues that the existing code triggers - it dings the code for weakening forgery protection. The forgery protection has to be turned off here because we're receiving POSTs from forms potentially created in other apps, which means we can't share forgery protection tokens easily. It's possible we could revisit this if this app is consolidated, but since that's unlikely, it's something we'll have to live with for the moment. 
⚠️  This …
=> Tidy up controller code
